/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from '@prisma/client/runtime/index-browser'

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal

export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as new (secret: never) => typeof runtime.DbNull,
  JsonNull: runtime.NullTypes.JsonNull as new (secret: never) => typeof runtime.JsonNull,
  AnyNull: runtime.NullTypes.AnyNull as new (secret: never) => typeof runtime.AnyNull,
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull

export const ModelName = {
  User: 'User',
  SourceOfIncomeCategory: 'SourceOfIncomeCategory',
  SourceOfIncome: 'SourceOfIncome',
  PaymentMethod: 'PaymentMethod',
  Expense: 'Expense',
  ExpensePaymentMethod: 'ExpensePaymentMethod',
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable',
} as const)

export type TransactionIsolationLevel =
  (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]

export const UserScalarFieldEnum = {
  id: 'id',
  external_id: 'external_id',
  created_at: 'created_at',
  updated_at: 'updated_at',
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]

export const SourceOfIncomeCategoryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  user_id: 'user_id',
  created_at: 'created_at',
  updated_at: 'updated_at',
} as const

export type SourceOfIncomeCategoryScalarFieldEnum =
  (typeof SourceOfIncomeCategoryScalarFieldEnum)[keyof typeof SourceOfIncomeCategoryScalarFieldEnum]

export const SourceOfIncomeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  category_id: 'category_id',
  income: 'income',
  user_id: 'user_id',
  created_at: 'created_at',
  updated_at: 'updated_at',
} as const

export type SourceOfIncomeScalarFieldEnum =
  (typeof SourceOfIncomeScalarFieldEnum)[keyof typeof SourceOfIncomeScalarFieldEnum]

export const PaymentMethodScalarFieldEnum = {
  id: 'id',
  name: 'name',
  origin: 'origin',
  receiver: 'receiver',
  user_id: 'user_id',
  created_at: 'created_at',
  updated_at: 'updated_at',
} as const

export type PaymentMethodScalarFieldEnum =
  (typeof PaymentMethodScalarFieldEnum)[keyof typeof PaymentMethodScalarFieldEnum]

export const ExpenseScalarFieldEnum = {
  id: 'id',
  name: 'name',
  amount: 'amount',
  is_paid: 'is_paid',
  is_saved: 'is_saved',
  saving_location: 'saving_location',
  user_id: 'user_id',
  created_at: 'created_at',
  updated_at: 'updated_at',
} as const

export type ExpenseScalarFieldEnum =
  (typeof ExpenseScalarFieldEnum)[keyof typeof ExpenseScalarFieldEnum]

export const ExpensePaymentMethodScalarFieldEnum = {
  expense_id: 'expense_id',
  payment_method_id: 'payment_method_id',
  partial_amount: 'partial_amount',
  created_at: 'created_at',
} as const

export type ExpensePaymentMethodScalarFieldEnum =
  (typeof ExpensePaymentMethodScalarFieldEnum)[keyof typeof ExpensePaymentMethodScalarFieldEnum]

export const SortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]

export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive',
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]

export const NullsOrder = {
  first: 'first',
  last: 'last',
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]
