/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `ExpensePaymentMethod` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/client'
import type * as $Enums from '../enums'
import type * as Prisma from '../internal/prismaNamespace'

/**
 * Model ExpensePaymentMethod
 *
 */
export type ExpensePaymentMethodModel =
  runtime.Types.Result.DefaultSelection<Prisma.$ExpensePaymentMethodPayload>

export type AggregateExpensePaymentMethod = {
  _count: ExpensePaymentMethodCountAggregateOutputType | null
  _avg: ExpensePaymentMethodAvgAggregateOutputType | null
  _sum: ExpensePaymentMethodSumAggregateOutputType | null
  _min: ExpensePaymentMethodMinAggregateOutputType | null
  _max: ExpensePaymentMethodMaxAggregateOutputType | null
}

export type ExpensePaymentMethodAvgAggregateOutputType = {
  expense_id: number | null
  payment_method_id: number | null
  partial_amount: number | null
}

export type ExpensePaymentMethodSumAggregateOutputType = {
  expense_id: bigint | null
  payment_method_id: bigint | null
  partial_amount: number | null
}

export type ExpensePaymentMethodMinAggregateOutputType = {
  expense_id: bigint | null
  payment_method_id: bigint | null
  partial_amount: number | null
  created_at: Date | null
}

export type ExpensePaymentMethodMaxAggregateOutputType = {
  expense_id: bigint | null
  payment_method_id: bigint | null
  partial_amount: number | null
  created_at: Date | null
}

export type ExpensePaymentMethodCountAggregateOutputType = {
  expense_id: number
  payment_method_id: number
  partial_amount: number
  created_at: number
  _all: number
}

export type ExpensePaymentMethodAvgAggregateInputType = {
  expense_id?: true
  payment_method_id?: true
  partial_amount?: true
}

export type ExpensePaymentMethodSumAggregateInputType = {
  expense_id?: true
  payment_method_id?: true
  partial_amount?: true
}

export type ExpensePaymentMethodMinAggregateInputType = {
  expense_id?: true
  payment_method_id?: true
  partial_amount?: true
  created_at?: true
}

export type ExpensePaymentMethodMaxAggregateInputType = {
  expense_id?: true
  payment_method_id?: true
  partial_amount?: true
  created_at?: true
}

export type ExpensePaymentMethodCountAggregateInputType = {
  expense_id?: true
  payment_method_id?: true
  partial_amount?: true
  created_at?: true
  _all?: true
}

export type ExpensePaymentMethodAggregateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which ExpensePaymentMethod to aggregate.
   */
  where?: Prisma.ExpensePaymentMethodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of ExpensePaymentMethods to fetch.
   */
  orderBy?:
    | Prisma.ExpensePaymentMethodOrderByWithRelationInput
    | Prisma.ExpensePaymentMethodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.ExpensePaymentMethodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` ExpensePaymentMethods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` ExpensePaymentMethods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned ExpensePaymentMethods
   **/
  _count?: true | ExpensePaymentMethodCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to average
   **/
  _avg?: ExpensePaymentMethodAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to sum
   **/
  _sum?: ExpensePaymentMethodSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: ExpensePaymentMethodMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: ExpensePaymentMethodMaxAggregateInputType
}

export type GetExpensePaymentMethodAggregateType<T extends ExpensePaymentMethodAggregateArgs> = {
  [P in keyof T & keyof AggregateExpensePaymentMethod]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateExpensePaymentMethod[P]>
    : Prisma.GetScalarType<T[P], AggregateExpensePaymentMethod[P]>
}

export type ExpensePaymentMethodGroupByArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.ExpensePaymentMethodWhereInput
  orderBy?:
    | Prisma.ExpensePaymentMethodOrderByWithAggregationInput
    | Prisma.ExpensePaymentMethodOrderByWithAggregationInput[]
  by: Prisma.ExpensePaymentMethodScalarFieldEnum[] | Prisma.ExpensePaymentMethodScalarFieldEnum
  having?: Prisma.ExpensePaymentMethodScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ExpensePaymentMethodCountAggregateInputType | true
  _avg?: ExpensePaymentMethodAvgAggregateInputType
  _sum?: ExpensePaymentMethodSumAggregateInputType
  _min?: ExpensePaymentMethodMinAggregateInputType
  _max?: ExpensePaymentMethodMaxAggregateInputType
}

export type ExpensePaymentMethodGroupByOutputType = {
  expense_id: bigint
  payment_method_id: bigint
  partial_amount: number
  created_at: Date
  _count: ExpensePaymentMethodCountAggregateOutputType | null
  _avg: ExpensePaymentMethodAvgAggregateOutputType | null
  _sum: ExpensePaymentMethodSumAggregateOutputType | null
  _min: ExpensePaymentMethodMinAggregateOutputType | null
  _max: ExpensePaymentMethodMaxAggregateOutputType | null
}

export type GetExpensePaymentMethodGroupByPayload<T extends ExpensePaymentMethodGroupByArgs> =
  Prisma.PrismaPromise<
    Array<
      Prisma.PickEnumerable<ExpensePaymentMethodGroupByOutputType, T['by']> & {
        [P in keyof T & keyof ExpensePaymentMethodGroupByOutputType]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ExpensePaymentMethodGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ExpensePaymentMethodGroupByOutputType[P]>
      }
    >
  >

export type ExpensePaymentMethodWhereInput = {
  AND?: Prisma.ExpensePaymentMethodWhereInput | Prisma.ExpensePaymentMethodWhereInput[]
  OR?: Prisma.ExpensePaymentMethodWhereInput[]
  NOT?: Prisma.ExpensePaymentMethodWhereInput | Prisma.ExpensePaymentMethodWhereInput[]
  expense_id?: Prisma.BigIntFilter<'ExpensePaymentMethod'> | bigint | number
  payment_method_id?: Prisma.BigIntFilter<'ExpensePaymentMethod'> | bigint | number
  partial_amount?: Prisma.FloatFilter<'ExpensePaymentMethod'> | number
  created_at?: Prisma.DateTimeFilter<'ExpensePaymentMethod'> | Date | string
  expense?: Prisma.XOR<Prisma.ExpenseScalarRelationFilter, Prisma.ExpenseWhereInput>
  payment_method?: Prisma.XOR<
    Prisma.PaymentMethodScalarRelationFilter,
    Prisma.PaymentMethodWhereInput
  >
}

export type ExpensePaymentMethodOrderByWithRelationInput = {
  expense_id?: Prisma.SortOrder
  payment_method_id?: Prisma.SortOrder
  partial_amount?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  expense?: Prisma.ExpenseOrderByWithRelationInput
  payment_method?: Prisma.PaymentMethodOrderByWithRelationInput
}

export type ExpensePaymentMethodWhereUniqueInput = Prisma.AtLeast<
  {
    expense_id_payment_method_id?: Prisma.ExpensePaymentMethodExpense_idPayment_method_idCompoundUniqueInput
    AND?: Prisma.ExpensePaymentMethodWhereInput | Prisma.ExpensePaymentMethodWhereInput[]
    OR?: Prisma.ExpensePaymentMethodWhereInput[]
    NOT?: Prisma.ExpensePaymentMethodWhereInput | Prisma.ExpensePaymentMethodWhereInput[]
    expense_id?: Prisma.BigIntFilter<'ExpensePaymentMethod'> | bigint | number
    payment_method_id?: Prisma.BigIntFilter<'ExpensePaymentMethod'> | bigint | number
    partial_amount?: Prisma.FloatFilter<'ExpensePaymentMethod'> | number
    created_at?: Prisma.DateTimeFilter<'ExpensePaymentMethod'> | Date | string
    expense?: Prisma.XOR<Prisma.ExpenseScalarRelationFilter, Prisma.ExpenseWhereInput>
    payment_method?: Prisma.XOR<
      Prisma.PaymentMethodScalarRelationFilter,
      Prisma.PaymentMethodWhereInput
    >
  },
  'expense_id_payment_method_id'
>

export type ExpensePaymentMethodOrderByWithAggregationInput = {
  expense_id?: Prisma.SortOrder
  payment_method_id?: Prisma.SortOrder
  partial_amount?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  _count?: Prisma.ExpensePaymentMethodCountOrderByAggregateInput
  _avg?: Prisma.ExpensePaymentMethodAvgOrderByAggregateInput
  _max?: Prisma.ExpensePaymentMethodMaxOrderByAggregateInput
  _min?: Prisma.ExpensePaymentMethodMinOrderByAggregateInput
  _sum?: Prisma.ExpensePaymentMethodSumOrderByAggregateInput
}

export type ExpensePaymentMethodScalarWhereWithAggregatesInput = {
  AND?:
    | Prisma.ExpensePaymentMethodScalarWhereWithAggregatesInput
    | Prisma.ExpensePaymentMethodScalarWhereWithAggregatesInput[]
  OR?: Prisma.ExpensePaymentMethodScalarWhereWithAggregatesInput[]
  NOT?:
    | Prisma.ExpensePaymentMethodScalarWhereWithAggregatesInput
    | Prisma.ExpensePaymentMethodScalarWhereWithAggregatesInput[]
  expense_id?: Prisma.BigIntWithAggregatesFilter<'ExpensePaymentMethod'> | bigint | number
  payment_method_id?: Prisma.BigIntWithAggregatesFilter<'ExpensePaymentMethod'> | bigint | number
  partial_amount?: Prisma.FloatWithAggregatesFilter<'ExpensePaymentMethod'> | number
  created_at?: Prisma.DateTimeWithAggregatesFilter<'ExpensePaymentMethod'> | Date | string
}

export type ExpensePaymentMethodCreateInput = {
  partial_amount: number
  created_at?: Date | string
  expense: Prisma.ExpenseCreateNestedOneWithoutPayment_methodsInput
  payment_method: Prisma.PaymentMethodCreateNestedOneWithoutExpensesInput
}

export type ExpensePaymentMethodUncheckedCreateInput = {
  expense_id: bigint | number
  payment_method_id: bigint | number
  partial_amount: number
  created_at?: Date | string
}

export type ExpensePaymentMethodUpdateInput = {
  partial_amount?: Prisma.FloatFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expense?: Prisma.ExpenseUpdateOneRequiredWithoutPayment_methodsNestedInput
  payment_method?: Prisma.PaymentMethodUpdateOneRequiredWithoutExpensesNestedInput
}

export type ExpensePaymentMethodUncheckedUpdateInput = {
  expense_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  payment_method_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  partial_amount?: Prisma.FloatFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ExpensePaymentMethodCreateManyInput = {
  expense_id: bigint | number
  payment_method_id: bigint | number
  partial_amount: number
  created_at?: Date | string
}

export type ExpensePaymentMethodUpdateManyMutationInput = {
  partial_amount?: Prisma.FloatFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ExpensePaymentMethodUncheckedUpdateManyInput = {
  expense_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  payment_method_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  partial_amount?: Prisma.FloatFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ExpensePaymentMethodListRelationFilter = {
  every?: Prisma.ExpensePaymentMethodWhereInput
  some?: Prisma.ExpensePaymentMethodWhereInput
  none?: Prisma.ExpensePaymentMethodWhereInput
}

export type ExpensePaymentMethodOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ExpensePaymentMethodExpense_idPayment_method_idCompoundUniqueInput = {
  expense_id: bigint | number
  payment_method_id: bigint | number
}

export type ExpensePaymentMethodCountOrderByAggregateInput = {
  expense_id?: Prisma.SortOrder
  payment_method_id?: Prisma.SortOrder
  partial_amount?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type ExpensePaymentMethodAvgOrderByAggregateInput = {
  expense_id?: Prisma.SortOrder
  payment_method_id?: Prisma.SortOrder
  partial_amount?: Prisma.SortOrder
}

export type ExpensePaymentMethodMaxOrderByAggregateInput = {
  expense_id?: Prisma.SortOrder
  payment_method_id?: Prisma.SortOrder
  partial_amount?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type ExpensePaymentMethodMinOrderByAggregateInput = {
  expense_id?: Prisma.SortOrder
  payment_method_id?: Prisma.SortOrder
  partial_amount?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type ExpensePaymentMethodSumOrderByAggregateInput = {
  expense_id?: Prisma.SortOrder
  payment_method_id?: Prisma.SortOrder
  partial_amount?: Prisma.SortOrder
}

export type ExpensePaymentMethodCreateNestedManyWithoutPayment_methodInput = {
  create?:
    | Prisma.XOR<
        Prisma.ExpensePaymentMethodCreateWithoutPayment_methodInput,
        Prisma.ExpensePaymentMethodUncheckedCreateWithoutPayment_methodInput
      >
    | Prisma.ExpensePaymentMethodCreateWithoutPayment_methodInput[]
    | Prisma.ExpensePaymentMethodUncheckedCreateWithoutPayment_methodInput[]
  connectOrCreate?:
    | Prisma.ExpensePaymentMethodCreateOrConnectWithoutPayment_methodInput
    | Prisma.ExpensePaymentMethodCreateOrConnectWithoutPayment_methodInput[]
  createMany?: Prisma.ExpensePaymentMethodCreateManyPayment_methodInputEnvelope
  connect?:
    | Prisma.ExpensePaymentMethodWhereUniqueInput
    | Prisma.ExpensePaymentMethodWhereUniqueInput[]
}

export type ExpensePaymentMethodUncheckedCreateNestedManyWithoutPayment_methodInput = {
  create?:
    | Prisma.XOR<
        Prisma.ExpensePaymentMethodCreateWithoutPayment_methodInput,
        Prisma.ExpensePaymentMethodUncheckedCreateWithoutPayment_methodInput
      >
    | Prisma.ExpensePaymentMethodCreateWithoutPayment_methodInput[]
    | Prisma.ExpensePaymentMethodUncheckedCreateWithoutPayment_methodInput[]
  connectOrCreate?:
    | Prisma.ExpensePaymentMethodCreateOrConnectWithoutPayment_methodInput
    | Prisma.ExpensePaymentMethodCreateOrConnectWithoutPayment_methodInput[]
  createMany?: Prisma.ExpensePaymentMethodCreateManyPayment_methodInputEnvelope
  connect?:
    | Prisma.ExpensePaymentMethodWhereUniqueInput
    | Prisma.ExpensePaymentMethodWhereUniqueInput[]
}

export type ExpensePaymentMethodUpdateManyWithoutPayment_methodNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.ExpensePaymentMethodCreateWithoutPayment_methodInput,
        Prisma.ExpensePaymentMethodUncheckedCreateWithoutPayment_methodInput
      >
    | Prisma.ExpensePaymentMethodCreateWithoutPayment_methodInput[]
    | Prisma.ExpensePaymentMethodUncheckedCreateWithoutPayment_methodInput[]
  connectOrCreate?:
    | Prisma.ExpensePaymentMethodCreateOrConnectWithoutPayment_methodInput
    | Prisma.ExpensePaymentMethodCreateOrConnectWithoutPayment_methodInput[]
  upsert?:
    | Prisma.ExpensePaymentMethodUpsertWithWhereUniqueWithoutPayment_methodInput
    | Prisma.ExpensePaymentMethodUpsertWithWhereUniqueWithoutPayment_methodInput[]
  createMany?: Prisma.ExpensePaymentMethodCreateManyPayment_methodInputEnvelope
  set?: Prisma.ExpensePaymentMethodWhereUniqueInput | Prisma.ExpensePaymentMethodWhereUniqueInput[]
  disconnect?:
    | Prisma.ExpensePaymentMethodWhereUniqueInput
    | Prisma.ExpensePaymentMethodWhereUniqueInput[]
  delete?:
    | Prisma.ExpensePaymentMethodWhereUniqueInput
    | Prisma.ExpensePaymentMethodWhereUniqueInput[]
  connect?:
    | Prisma.ExpensePaymentMethodWhereUniqueInput
    | Prisma.ExpensePaymentMethodWhereUniqueInput[]
  update?:
    | Prisma.ExpensePaymentMethodUpdateWithWhereUniqueWithoutPayment_methodInput
    | Prisma.ExpensePaymentMethodUpdateWithWhereUniqueWithoutPayment_methodInput[]
  updateMany?:
    | Prisma.ExpensePaymentMethodUpdateManyWithWhereWithoutPayment_methodInput
    | Prisma.ExpensePaymentMethodUpdateManyWithWhereWithoutPayment_methodInput[]
  deleteMany?:
    | Prisma.ExpensePaymentMethodScalarWhereInput
    | Prisma.ExpensePaymentMethodScalarWhereInput[]
}

export type ExpensePaymentMethodUncheckedUpdateManyWithoutPayment_methodNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.ExpensePaymentMethodCreateWithoutPayment_methodInput,
        Prisma.ExpensePaymentMethodUncheckedCreateWithoutPayment_methodInput
      >
    | Prisma.ExpensePaymentMethodCreateWithoutPayment_methodInput[]
    | Prisma.ExpensePaymentMethodUncheckedCreateWithoutPayment_methodInput[]
  connectOrCreate?:
    | Prisma.ExpensePaymentMethodCreateOrConnectWithoutPayment_methodInput
    | Prisma.ExpensePaymentMethodCreateOrConnectWithoutPayment_methodInput[]
  upsert?:
    | Prisma.ExpensePaymentMethodUpsertWithWhereUniqueWithoutPayment_methodInput
    | Prisma.ExpensePaymentMethodUpsertWithWhereUniqueWithoutPayment_methodInput[]
  createMany?: Prisma.ExpensePaymentMethodCreateManyPayment_methodInputEnvelope
  set?: Prisma.ExpensePaymentMethodWhereUniqueInput | Prisma.ExpensePaymentMethodWhereUniqueInput[]
  disconnect?:
    | Prisma.ExpensePaymentMethodWhereUniqueInput
    | Prisma.ExpensePaymentMethodWhereUniqueInput[]
  delete?:
    | Prisma.ExpensePaymentMethodWhereUniqueInput
    | Prisma.ExpensePaymentMethodWhereUniqueInput[]
  connect?:
    | Prisma.ExpensePaymentMethodWhereUniqueInput
    | Prisma.ExpensePaymentMethodWhereUniqueInput[]
  update?:
    | Prisma.ExpensePaymentMethodUpdateWithWhereUniqueWithoutPayment_methodInput
    | Prisma.ExpensePaymentMethodUpdateWithWhereUniqueWithoutPayment_methodInput[]
  updateMany?:
    | Prisma.ExpensePaymentMethodUpdateManyWithWhereWithoutPayment_methodInput
    | Prisma.ExpensePaymentMethodUpdateManyWithWhereWithoutPayment_methodInput[]
  deleteMany?:
    | Prisma.ExpensePaymentMethodScalarWhereInput
    | Prisma.ExpensePaymentMethodScalarWhereInput[]
}

export type ExpensePaymentMethodCreateNestedManyWithoutExpenseInput = {
  create?:
    | Prisma.XOR<
        Prisma.ExpensePaymentMethodCreateWithoutExpenseInput,
        Prisma.ExpensePaymentMethodUncheckedCreateWithoutExpenseInput
      >
    | Prisma.ExpensePaymentMethodCreateWithoutExpenseInput[]
    | Prisma.ExpensePaymentMethodUncheckedCreateWithoutExpenseInput[]
  connectOrCreate?:
    | Prisma.ExpensePaymentMethodCreateOrConnectWithoutExpenseInput
    | Prisma.ExpensePaymentMethodCreateOrConnectWithoutExpenseInput[]
  createMany?: Prisma.ExpensePaymentMethodCreateManyExpenseInputEnvelope
  connect?:
    | Prisma.ExpensePaymentMethodWhereUniqueInput
    | Prisma.ExpensePaymentMethodWhereUniqueInput[]
}

export type ExpensePaymentMethodUncheckedCreateNestedManyWithoutExpenseInput = {
  create?:
    | Prisma.XOR<
        Prisma.ExpensePaymentMethodCreateWithoutExpenseInput,
        Prisma.ExpensePaymentMethodUncheckedCreateWithoutExpenseInput
      >
    | Prisma.ExpensePaymentMethodCreateWithoutExpenseInput[]
    | Prisma.ExpensePaymentMethodUncheckedCreateWithoutExpenseInput[]
  connectOrCreate?:
    | Prisma.ExpensePaymentMethodCreateOrConnectWithoutExpenseInput
    | Prisma.ExpensePaymentMethodCreateOrConnectWithoutExpenseInput[]
  createMany?: Prisma.ExpensePaymentMethodCreateManyExpenseInputEnvelope
  connect?:
    | Prisma.ExpensePaymentMethodWhereUniqueInput
    | Prisma.ExpensePaymentMethodWhereUniqueInput[]
}

export type ExpensePaymentMethodUpdateManyWithoutExpenseNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.ExpensePaymentMethodCreateWithoutExpenseInput,
        Prisma.ExpensePaymentMethodUncheckedCreateWithoutExpenseInput
      >
    | Prisma.ExpensePaymentMethodCreateWithoutExpenseInput[]
    | Prisma.ExpensePaymentMethodUncheckedCreateWithoutExpenseInput[]
  connectOrCreate?:
    | Prisma.ExpensePaymentMethodCreateOrConnectWithoutExpenseInput
    | Prisma.ExpensePaymentMethodCreateOrConnectWithoutExpenseInput[]
  upsert?:
    | Prisma.ExpensePaymentMethodUpsertWithWhereUniqueWithoutExpenseInput
    | Prisma.ExpensePaymentMethodUpsertWithWhereUniqueWithoutExpenseInput[]
  createMany?: Prisma.ExpensePaymentMethodCreateManyExpenseInputEnvelope
  set?: Prisma.ExpensePaymentMethodWhereUniqueInput | Prisma.ExpensePaymentMethodWhereUniqueInput[]
  disconnect?:
    | Prisma.ExpensePaymentMethodWhereUniqueInput
    | Prisma.ExpensePaymentMethodWhereUniqueInput[]
  delete?:
    | Prisma.ExpensePaymentMethodWhereUniqueInput
    | Prisma.ExpensePaymentMethodWhereUniqueInput[]
  connect?:
    | Prisma.ExpensePaymentMethodWhereUniqueInput
    | Prisma.ExpensePaymentMethodWhereUniqueInput[]
  update?:
    | Prisma.ExpensePaymentMethodUpdateWithWhereUniqueWithoutExpenseInput
    | Prisma.ExpensePaymentMethodUpdateWithWhereUniqueWithoutExpenseInput[]
  updateMany?:
    | Prisma.ExpensePaymentMethodUpdateManyWithWhereWithoutExpenseInput
    | Prisma.ExpensePaymentMethodUpdateManyWithWhereWithoutExpenseInput[]
  deleteMany?:
    | Prisma.ExpensePaymentMethodScalarWhereInput
    | Prisma.ExpensePaymentMethodScalarWhereInput[]
}

export type ExpensePaymentMethodUncheckedUpdateManyWithoutExpenseNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.ExpensePaymentMethodCreateWithoutExpenseInput,
        Prisma.ExpensePaymentMethodUncheckedCreateWithoutExpenseInput
      >
    | Prisma.ExpensePaymentMethodCreateWithoutExpenseInput[]
    | Prisma.ExpensePaymentMethodUncheckedCreateWithoutExpenseInput[]
  connectOrCreate?:
    | Prisma.ExpensePaymentMethodCreateOrConnectWithoutExpenseInput
    | Prisma.ExpensePaymentMethodCreateOrConnectWithoutExpenseInput[]
  upsert?:
    | Prisma.ExpensePaymentMethodUpsertWithWhereUniqueWithoutExpenseInput
    | Prisma.ExpensePaymentMethodUpsertWithWhereUniqueWithoutExpenseInput[]
  createMany?: Prisma.ExpensePaymentMethodCreateManyExpenseInputEnvelope
  set?: Prisma.ExpensePaymentMethodWhereUniqueInput | Prisma.ExpensePaymentMethodWhereUniqueInput[]
  disconnect?:
    | Prisma.ExpensePaymentMethodWhereUniqueInput
    | Prisma.ExpensePaymentMethodWhereUniqueInput[]
  delete?:
    | Prisma.ExpensePaymentMethodWhereUniqueInput
    | Prisma.ExpensePaymentMethodWhereUniqueInput[]
  connect?:
    | Prisma.ExpensePaymentMethodWhereUniqueInput
    | Prisma.ExpensePaymentMethodWhereUniqueInput[]
  update?:
    | Prisma.ExpensePaymentMethodUpdateWithWhereUniqueWithoutExpenseInput
    | Prisma.ExpensePaymentMethodUpdateWithWhereUniqueWithoutExpenseInput[]
  updateMany?:
    | Prisma.ExpensePaymentMethodUpdateManyWithWhereWithoutExpenseInput
    | Prisma.ExpensePaymentMethodUpdateManyWithWhereWithoutExpenseInput[]
  deleteMany?:
    | Prisma.ExpensePaymentMethodScalarWhereInput
    | Prisma.ExpensePaymentMethodScalarWhereInput[]
}

export type ExpensePaymentMethodCreateWithoutPayment_methodInput = {
  partial_amount: number
  created_at?: Date | string
  expense: Prisma.ExpenseCreateNestedOneWithoutPayment_methodsInput
}

export type ExpensePaymentMethodUncheckedCreateWithoutPayment_methodInput = {
  expense_id: bigint | number
  partial_amount: number
  created_at?: Date | string
}

export type ExpensePaymentMethodCreateOrConnectWithoutPayment_methodInput = {
  where: Prisma.ExpensePaymentMethodWhereUniqueInput
  create: Prisma.XOR<
    Prisma.ExpensePaymentMethodCreateWithoutPayment_methodInput,
    Prisma.ExpensePaymentMethodUncheckedCreateWithoutPayment_methodInput
  >
}

export type ExpensePaymentMethodCreateManyPayment_methodInputEnvelope = {
  data:
    | Prisma.ExpensePaymentMethodCreateManyPayment_methodInput
    | Prisma.ExpensePaymentMethodCreateManyPayment_methodInput[]
  skipDuplicates?: boolean
}

export type ExpensePaymentMethodUpsertWithWhereUniqueWithoutPayment_methodInput = {
  where: Prisma.ExpensePaymentMethodWhereUniqueInput
  update: Prisma.XOR<
    Prisma.ExpensePaymentMethodUpdateWithoutPayment_methodInput,
    Prisma.ExpensePaymentMethodUncheckedUpdateWithoutPayment_methodInput
  >
  create: Prisma.XOR<
    Prisma.ExpensePaymentMethodCreateWithoutPayment_methodInput,
    Prisma.ExpensePaymentMethodUncheckedCreateWithoutPayment_methodInput
  >
}

export type ExpensePaymentMethodUpdateWithWhereUniqueWithoutPayment_methodInput = {
  where: Prisma.ExpensePaymentMethodWhereUniqueInput
  data: Prisma.XOR<
    Prisma.ExpensePaymentMethodUpdateWithoutPayment_methodInput,
    Prisma.ExpensePaymentMethodUncheckedUpdateWithoutPayment_methodInput
  >
}

export type ExpensePaymentMethodUpdateManyWithWhereWithoutPayment_methodInput = {
  where: Prisma.ExpensePaymentMethodScalarWhereInput
  data: Prisma.XOR<
    Prisma.ExpensePaymentMethodUpdateManyMutationInput,
    Prisma.ExpensePaymentMethodUncheckedUpdateManyWithoutPayment_methodInput
  >
}

export type ExpensePaymentMethodScalarWhereInput = {
  AND?: Prisma.ExpensePaymentMethodScalarWhereInput | Prisma.ExpensePaymentMethodScalarWhereInput[]
  OR?: Prisma.ExpensePaymentMethodScalarWhereInput[]
  NOT?: Prisma.ExpensePaymentMethodScalarWhereInput | Prisma.ExpensePaymentMethodScalarWhereInput[]
  expense_id?: Prisma.BigIntFilter<'ExpensePaymentMethod'> | bigint | number
  payment_method_id?: Prisma.BigIntFilter<'ExpensePaymentMethod'> | bigint | number
  partial_amount?: Prisma.FloatFilter<'ExpensePaymentMethod'> | number
  created_at?: Prisma.DateTimeFilter<'ExpensePaymentMethod'> | Date | string
}

export type ExpensePaymentMethodCreateWithoutExpenseInput = {
  partial_amount: number
  created_at?: Date | string
  payment_method: Prisma.PaymentMethodCreateNestedOneWithoutExpensesInput
}

export type ExpensePaymentMethodUncheckedCreateWithoutExpenseInput = {
  payment_method_id: bigint | number
  partial_amount: number
  created_at?: Date | string
}

export type ExpensePaymentMethodCreateOrConnectWithoutExpenseInput = {
  where: Prisma.ExpensePaymentMethodWhereUniqueInput
  create: Prisma.XOR<
    Prisma.ExpensePaymentMethodCreateWithoutExpenseInput,
    Prisma.ExpensePaymentMethodUncheckedCreateWithoutExpenseInput
  >
}

export type ExpensePaymentMethodCreateManyExpenseInputEnvelope = {
  data:
    | Prisma.ExpensePaymentMethodCreateManyExpenseInput
    | Prisma.ExpensePaymentMethodCreateManyExpenseInput[]
  skipDuplicates?: boolean
}

export type ExpensePaymentMethodUpsertWithWhereUniqueWithoutExpenseInput = {
  where: Prisma.ExpensePaymentMethodWhereUniqueInput
  update: Prisma.XOR<
    Prisma.ExpensePaymentMethodUpdateWithoutExpenseInput,
    Prisma.ExpensePaymentMethodUncheckedUpdateWithoutExpenseInput
  >
  create: Prisma.XOR<
    Prisma.ExpensePaymentMethodCreateWithoutExpenseInput,
    Prisma.ExpensePaymentMethodUncheckedCreateWithoutExpenseInput
  >
}

export type ExpensePaymentMethodUpdateWithWhereUniqueWithoutExpenseInput = {
  where: Prisma.ExpensePaymentMethodWhereUniqueInput
  data: Prisma.XOR<
    Prisma.ExpensePaymentMethodUpdateWithoutExpenseInput,
    Prisma.ExpensePaymentMethodUncheckedUpdateWithoutExpenseInput
  >
}

export type ExpensePaymentMethodUpdateManyWithWhereWithoutExpenseInput = {
  where: Prisma.ExpensePaymentMethodScalarWhereInput
  data: Prisma.XOR<
    Prisma.ExpensePaymentMethodUpdateManyMutationInput,
    Prisma.ExpensePaymentMethodUncheckedUpdateManyWithoutExpenseInput
  >
}

export type ExpensePaymentMethodCreateManyPayment_methodInput = {
  expense_id: bigint | number
  partial_amount: number
  created_at?: Date | string
}

export type ExpensePaymentMethodUpdateWithoutPayment_methodInput = {
  partial_amount?: Prisma.FloatFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expense?: Prisma.ExpenseUpdateOneRequiredWithoutPayment_methodsNestedInput
}

export type ExpensePaymentMethodUncheckedUpdateWithoutPayment_methodInput = {
  expense_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  partial_amount?: Prisma.FloatFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ExpensePaymentMethodUncheckedUpdateManyWithoutPayment_methodInput = {
  expense_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  partial_amount?: Prisma.FloatFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ExpensePaymentMethodCreateManyExpenseInput = {
  payment_method_id: bigint | number
  partial_amount: number
  created_at?: Date | string
}

export type ExpensePaymentMethodUpdateWithoutExpenseInput = {
  partial_amount?: Prisma.FloatFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  payment_method?: Prisma.PaymentMethodUpdateOneRequiredWithoutExpensesNestedInput
}

export type ExpensePaymentMethodUncheckedUpdateWithoutExpenseInput = {
  payment_method_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  partial_amount?: Prisma.FloatFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ExpensePaymentMethodUncheckedUpdateManyWithoutExpenseInput = {
  payment_method_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  partial_amount?: Prisma.FloatFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ExpensePaymentMethodSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    expense_id?: boolean
    payment_method_id?: boolean
    partial_amount?: boolean
    created_at?: boolean
    expense?: boolean | Prisma.ExpenseDefaultArgs<ExtArgs>
    payment_method?: boolean | Prisma.PaymentMethodDefaultArgs<ExtArgs>
  },
  ExtArgs['result']['expensePaymentMethod']
>

export type ExpensePaymentMethodSelectCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    expense_id?: boolean
    payment_method_id?: boolean
    partial_amount?: boolean
    created_at?: boolean
    expense?: boolean | Prisma.ExpenseDefaultArgs<ExtArgs>
    payment_method?: boolean | Prisma.PaymentMethodDefaultArgs<ExtArgs>
  },
  ExtArgs['result']['expensePaymentMethod']
>

export type ExpensePaymentMethodSelectUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    expense_id?: boolean
    payment_method_id?: boolean
    partial_amount?: boolean
    created_at?: boolean
    expense?: boolean | Prisma.ExpenseDefaultArgs<ExtArgs>
    payment_method?: boolean | Prisma.PaymentMethodDefaultArgs<ExtArgs>
  },
  ExtArgs['result']['expensePaymentMethod']
>

export type ExpensePaymentMethodSelectScalar = {
  expense_id?: boolean
  payment_method_id?: boolean
  partial_amount?: boolean
  created_at?: boolean
}

export type ExpensePaymentMethodOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  'expense_id' | 'payment_method_id' | 'partial_amount' | 'created_at',
  ExtArgs['result']['expensePaymentMethod']
>
export type ExpensePaymentMethodInclude<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  expense?: boolean | Prisma.ExpenseDefaultArgs<ExtArgs>
  payment_method?: boolean | Prisma.PaymentMethodDefaultArgs<ExtArgs>
}
export type ExpensePaymentMethodIncludeCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  expense?: boolean | Prisma.ExpenseDefaultArgs<ExtArgs>
  payment_method?: boolean | Prisma.PaymentMethodDefaultArgs<ExtArgs>
}
export type ExpensePaymentMethodIncludeUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  expense?: boolean | Prisma.ExpenseDefaultArgs<ExtArgs>
  payment_method?: boolean | Prisma.PaymentMethodDefaultArgs<ExtArgs>
}

export type $ExpensePaymentMethodPayload<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  name: 'ExpensePaymentMethod'
  objects: {
    expense: Prisma.$ExpensePayload<ExtArgs>
    payment_method: Prisma.$PaymentMethodPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      expense_id: bigint
      payment_method_id: bigint
      partial_amount: number
      created_at: Date
    },
    ExtArgs['result']['expensePaymentMethod']
  >
  composites: {}
}

export type ExpensePaymentMethodGetPayload<
  S extends boolean | null | undefined | ExpensePaymentMethodDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$ExpensePaymentMethodPayload, S>

export type ExpensePaymentMethodCountArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = Omit<ExpensePaymentMethodFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
  select?: ExpensePaymentMethodCountAggregateInputType | true
}

export interface ExpensePaymentMethodDelegate<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>['model']['ExpensePaymentMethod']
    meta: { name: 'ExpensePaymentMethod' }
  }
  /**
   * Find zero or one ExpensePaymentMethod that matches the filter.
   * @param {ExpensePaymentMethodFindUniqueArgs} args - Arguments to find a ExpensePaymentMethod
   * @example
   * // Get one ExpensePaymentMethod
   * const expensePaymentMethod = await prisma.expensePaymentMethod.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ExpensePaymentMethodFindUniqueArgs>(
    args: Prisma.SelectSubset<T, ExpensePaymentMethodFindUniqueArgs<ExtArgs>>
  ): Prisma.Prisma__ExpensePaymentMethodClient<
    runtime.Types.Result.GetResult<
      Prisma.$ExpensePaymentMethodPayload<ExtArgs>,
      T,
      'findUnique',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find one ExpensePaymentMethod that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ExpensePaymentMethodFindUniqueOrThrowArgs} args - Arguments to find a ExpensePaymentMethod
   * @example
   * // Get one ExpensePaymentMethod
   * const expensePaymentMethod = await prisma.expensePaymentMethod.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ExpensePaymentMethodFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<T, ExpensePaymentMethodFindUniqueOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__ExpensePaymentMethodClient<
    runtime.Types.Result.GetResult<
      Prisma.$ExpensePaymentMethodPayload<ExtArgs>,
      T,
      'findUniqueOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find the first ExpensePaymentMethod that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExpensePaymentMethodFindFirstArgs} args - Arguments to find a ExpensePaymentMethod
   * @example
   * // Get one ExpensePaymentMethod
   * const expensePaymentMethod = await prisma.expensePaymentMethod.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ExpensePaymentMethodFindFirstArgs>(
    args?: Prisma.SelectSubset<T, ExpensePaymentMethodFindFirstArgs<ExtArgs>>
  ): Prisma.Prisma__ExpensePaymentMethodClient<
    runtime.Types.Result.GetResult<
      Prisma.$ExpensePaymentMethodPayload<ExtArgs>,
      T,
      'findFirst',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find the first ExpensePaymentMethod that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExpensePaymentMethodFindFirstOrThrowArgs} args - Arguments to find a ExpensePaymentMethod
   * @example
   * // Get one ExpensePaymentMethod
   * const expensePaymentMethod = await prisma.expensePaymentMethod.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ExpensePaymentMethodFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<T, ExpensePaymentMethodFindFirstOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__ExpensePaymentMethodClient<
    runtime.Types.Result.GetResult<
      Prisma.$ExpensePaymentMethodPayload<ExtArgs>,
      T,
      'findFirstOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find zero or more ExpensePaymentMethods that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExpensePaymentMethodFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ExpensePaymentMethods
   * const expensePaymentMethods = await prisma.expensePaymentMethod.findMany()
   *
   * // Get first 10 ExpensePaymentMethods
   * const expensePaymentMethods = await prisma.expensePaymentMethod.findMany({ take: 10 })
   *
   * // Only select the `expense_id`
   * const expensePaymentMethodWithExpense_idOnly = await prisma.expensePaymentMethod.findMany({ select: { expense_id: true } })
   *
   */
  findMany<T extends ExpensePaymentMethodFindManyArgs>(
    args?: Prisma.SelectSubset<T, ExpensePaymentMethodFindManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$ExpensePaymentMethodPayload<ExtArgs>,
      T,
      'findMany',
      GlobalOmitOptions
    >
  >

  /**
   * Create a ExpensePaymentMethod.
   * @param {ExpensePaymentMethodCreateArgs} args - Arguments to create a ExpensePaymentMethod.
   * @example
   * // Create one ExpensePaymentMethod
   * const ExpensePaymentMethod = await prisma.expensePaymentMethod.create({
   *   data: {
   *     // ... data to create a ExpensePaymentMethod
   *   }
   * })
   *
   */
  create<T extends ExpensePaymentMethodCreateArgs>(
    args: Prisma.SelectSubset<T, ExpensePaymentMethodCreateArgs<ExtArgs>>
  ): Prisma.Prisma__ExpensePaymentMethodClient<
    runtime.Types.Result.GetResult<
      Prisma.$ExpensePaymentMethodPayload<ExtArgs>,
      T,
      'create',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Create many ExpensePaymentMethods.
   * @param {ExpensePaymentMethodCreateManyArgs} args - Arguments to create many ExpensePaymentMethods.
   * @example
   * // Create many ExpensePaymentMethods
   * const expensePaymentMethod = await prisma.expensePaymentMethod.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends ExpensePaymentMethodCreateManyArgs>(
    args?: Prisma.SelectSubset<T, ExpensePaymentMethodCreateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ExpensePaymentMethods and returns the data saved in the database.
   * @param {ExpensePaymentMethodCreateManyAndReturnArgs} args - Arguments to create many ExpensePaymentMethods.
   * @example
   * // Create many ExpensePaymentMethods
   * const expensePaymentMethod = await prisma.expensePaymentMethod.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many ExpensePaymentMethods and only return the `expense_id`
   * const expensePaymentMethodWithExpense_idOnly = await prisma.expensePaymentMethod.createManyAndReturn({
   *   select: { expense_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends ExpensePaymentMethodCreateManyAndReturnArgs>(
    args?: Prisma.SelectSubset<T, ExpensePaymentMethodCreateManyAndReturnArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$ExpensePaymentMethodPayload<ExtArgs>,
      T,
      'createManyAndReturn',
      GlobalOmitOptions
    >
  >

  /**
   * Delete a ExpensePaymentMethod.
   * @param {ExpensePaymentMethodDeleteArgs} args - Arguments to delete one ExpensePaymentMethod.
   * @example
   * // Delete one ExpensePaymentMethod
   * const ExpensePaymentMethod = await prisma.expensePaymentMethod.delete({
   *   where: {
   *     // ... filter to delete one ExpensePaymentMethod
   *   }
   * })
   *
   */
  delete<T extends ExpensePaymentMethodDeleteArgs>(
    args: Prisma.SelectSubset<T, ExpensePaymentMethodDeleteArgs<ExtArgs>>
  ): Prisma.Prisma__ExpensePaymentMethodClient<
    runtime.Types.Result.GetResult<
      Prisma.$ExpensePaymentMethodPayload<ExtArgs>,
      T,
      'delete',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Update one ExpensePaymentMethod.
   * @param {ExpensePaymentMethodUpdateArgs} args - Arguments to update one ExpensePaymentMethod.
   * @example
   * // Update one ExpensePaymentMethod
   * const expensePaymentMethod = await prisma.expensePaymentMethod.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends ExpensePaymentMethodUpdateArgs>(
    args: Prisma.SelectSubset<T, ExpensePaymentMethodUpdateArgs<ExtArgs>>
  ): Prisma.Prisma__ExpensePaymentMethodClient<
    runtime.Types.Result.GetResult<
      Prisma.$ExpensePaymentMethodPayload<ExtArgs>,
      T,
      'update',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Delete zero or more ExpensePaymentMethods.
   * @param {ExpensePaymentMethodDeleteManyArgs} args - Arguments to filter ExpensePaymentMethods to delete.
   * @example
   * // Delete a few ExpensePaymentMethods
   * const { count } = await prisma.expensePaymentMethod.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends ExpensePaymentMethodDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, ExpensePaymentMethodDeleteManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ExpensePaymentMethods.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExpensePaymentMethodUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ExpensePaymentMethods
   * const expensePaymentMethod = await prisma.expensePaymentMethod.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends ExpensePaymentMethodUpdateManyArgs>(
    args: Prisma.SelectSubset<T, ExpensePaymentMethodUpdateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ExpensePaymentMethods and returns the data updated in the database.
   * @param {ExpensePaymentMethodUpdateManyAndReturnArgs} args - Arguments to update many ExpensePaymentMethods.
   * @example
   * // Update many ExpensePaymentMethods
   * const expensePaymentMethod = await prisma.expensePaymentMethod.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more ExpensePaymentMethods and only return the `expense_id`
   * const expensePaymentMethodWithExpense_idOnly = await prisma.expensePaymentMethod.updateManyAndReturn({
   *   select: { expense_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends ExpensePaymentMethodUpdateManyAndReturnArgs>(
    args: Prisma.SelectSubset<T, ExpensePaymentMethodUpdateManyAndReturnArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$ExpensePaymentMethodPayload<ExtArgs>,
      T,
      'updateManyAndReturn',
      GlobalOmitOptions
    >
  >

  /**
   * Create or update one ExpensePaymentMethod.
   * @param {ExpensePaymentMethodUpsertArgs} args - Arguments to update or create a ExpensePaymentMethod.
   * @example
   * // Update or create a ExpensePaymentMethod
   * const expensePaymentMethod = await prisma.expensePaymentMethod.upsert({
   *   create: {
   *     // ... data to create a ExpensePaymentMethod
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ExpensePaymentMethod we want to update
   *   }
   * })
   */
  upsert<T extends ExpensePaymentMethodUpsertArgs>(
    args: Prisma.SelectSubset<T, ExpensePaymentMethodUpsertArgs<ExtArgs>>
  ): Prisma.Prisma__ExpensePaymentMethodClient<
    runtime.Types.Result.GetResult<
      Prisma.$ExpensePaymentMethodPayload<ExtArgs>,
      T,
      'upsert',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Count the number of ExpensePaymentMethods.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExpensePaymentMethodCountArgs} args - Arguments to filter ExpensePaymentMethods to count.
   * @example
   * // Count the number of ExpensePaymentMethods
   * const count = await prisma.expensePaymentMethod.count({
   *   where: {
   *     // ... the filter for the ExpensePaymentMethods we want to count
   *   }
   * })
   **/
  count<T extends ExpensePaymentMethodCountArgs>(
    args?: Prisma.Subset<T, ExpensePaymentMethodCountArgs>
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ExpensePaymentMethodCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ExpensePaymentMethod.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExpensePaymentMethodAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends ExpensePaymentMethodAggregateArgs>(
    args: Prisma.Subset<T, ExpensePaymentMethodAggregateArgs>
  ): Prisma.PrismaPromise<GetExpensePaymentMethodAggregateType<T>>

  /**
   * Group by ExpensePaymentMethod.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExpensePaymentMethodGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends ExpensePaymentMethodGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ExpensePaymentMethodGroupByArgs['orderBy'] }
      : { orderBy?: ExpensePaymentMethodGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [Error, 'Field ', P, ` in "having" needs to be provided in "by"`]
          }[HavingFields]
        : 'take' extends Prisma.Keys<T>
          ? 'orderBy' extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : 'skip' extends Prisma.Keys<T>
            ? 'orderBy' extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields],
  >(
    args: Prisma.SubsetIntersection<T, ExpensePaymentMethodGroupByArgs, OrderByArg> & InputErrors
  ): {} extends InputErrors
    ? GetExpensePaymentMethodGroupByPayload<T>
    : Prisma.PrismaPromise<InputErrors>
  /**
   * Fields of the ExpensePaymentMethod model
   */
  readonly fields: ExpensePaymentMethodFieldRefs
}

/**
 * The delegate class that acts as a "Promise-like" for ExpensePaymentMethod.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ExpensePaymentMethodClient<
  T,
  Null = never,
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: 'PrismaPromise'
  expense<T extends Prisma.ExpenseDefaultArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.ExpenseDefaultArgs<ExtArgs>>
  ): Prisma.Prisma__ExpenseClient<
    | runtime.Types.Result.GetResult<
        Prisma.$ExpensePayload<ExtArgs>,
        T,
        'findUniqueOrThrow',
        GlobalOmitOptions
      >
    | Null,
    Null,
    ExtArgs,
    GlobalOmitOptions
  >
  payment_method<T extends Prisma.PaymentMethodDefaultArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.PaymentMethodDefaultArgs<ExtArgs>>
  ): Prisma.Prisma__PaymentMethodClient<
    | runtime.Types.Result.GetResult<
        Prisma.$PaymentMethodPayload<ExtArgs>,
        T,
        'findUniqueOrThrow',
        GlobalOmitOptions
      >
    | Null,
    Null,
    ExtArgs,
    GlobalOmitOptions
  >
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null,
    onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null
  ): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}

/**
 * Fields of the ExpensePaymentMethod model
 */
export interface ExpensePaymentMethodFieldRefs {
  readonly expense_id: Prisma.FieldRef<'ExpensePaymentMethod', 'BigInt'>
  readonly payment_method_id: Prisma.FieldRef<'ExpensePaymentMethod', 'BigInt'>
  readonly partial_amount: Prisma.FieldRef<'ExpensePaymentMethod', 'Float'>
  readonly created_at: Prisma.FieldRef<'ExpensePaymentMethod', 'DateTime'>
}

// Custom InputTypes
/**
 * ExpensePaymentMethod findUnique
 */
export type ExpensePaymentMethodFindUniqueArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ExpensePaymentMethod
   */
  select?: Prisma.ExpensePaymentMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExpensePaymentMethod
   */
  omit?: Prisma.ExpensePaymentMethodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExpensePaymentMethodInclude<ExtArgs> | null
  /**
   * Filter, which ExpensePaymentMethod to fetch.
   */
  where: Prisma.ExpensePaymentMethodWhereUniqueInput
}

/**
 * ExpensePaymentMethod findUniqueOrThrow
 */
export type ExpensePaymentMethodFindUniqueOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ExpensePaymentMethod
   */
  select?: Prisma.ExpensePaymentMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExpensePaymentMethod
   */
  omit?: Prisma.ExpensePaymentMethodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExpensePaymentMethodInclude<ExtArgs> | null
  /**
   * Filter, which ExpensePaymentMethod to fetch.
   */
  where: Prisma.ExpensePaymentMethodWhereUniqueInput
}

/**
 * ExpensePaymentMethod findFirst
 */
export type ExpensePaymentMethodFindFirstArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ExpensePaymentMethod
   */
  select?: Prisma.ExpensePaymentMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExpensePaymentMethod
   */
  omit?: Prisma.ExpensePaymentMethodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExpensePaymentMethodInclude<ExtArgs> | null
  /**
   * Filter, which ExpensePaymentMethod to fetch.
   */
  where?: Prisma.ExpensePaymentMethodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of ExpensePaymentMethods to fetch.
   */
  orderBy?:
    | Prisma.ExpensePaymentMethodOrderByWithRelationInput
    | Prisma.ExpensePaymentMethodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for ExpensePaymentMethods.
   */
  cursor?: Prisma.ExpensePaymentMethodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` ExpensePaymentMethods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` ExpensePaymentMethods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of ExpensePaymentMethods.
   */
  distinct?:
    | Prisma.ExpensePaymentMethodScalarFieldEnum
    | Prisma.ExpensePaymentMethodScalarFieldEnum[]
}

/**
 * ExpensePaymentMethod findFirstOrThrow
 */
export type ExpensePaymentMethodFindFirstOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ExpensePaymentMethod
   */
  select?: Prisma.ExpensePaymentMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExpensePaymentMethod
   */
  omit?: Prisma.ExpensePaymentMethodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExpensePaymentMethodInclude<ExtArgs> | null
  /**
   * Filter, which ExpensePaymentMethod to fetch.
   */
  where?: Prisma.ExpensePaymentMethodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of ExpensePaymentMethods to fetch.
   */
  orderBy?:
    | Prisma.ExpensePaymentMethodOrderByWithRelationInput
    | Prisma.ExpensePaymentMethodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for ExpensePaymentMethods.
   */
  cursor?: Prisma.ExpensePaymentMethodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` ExpensePaymentMethods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` ExpensePaymentMethods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of ExpensePaymentMethods.
   */
  distinct?:
    | Prisma.ExpensePaymentMethodScalarFieldEnum
    | Prisma.ExpensePaymentMethodScalarFieldEnum[]
}

/**
 * ExpensePaymentMethod findMany
 */
export type ExpensePaymentMethodFindManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ExpensePaymentMethod
   */
  select?: Prisma.ExpensePaymentMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExpensePaymentMethod
   */
  omit?: Prisma.ExpensePaymentMethodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExpensePaymentMethodInclude<ExtArgs> | null
  /**
   * Filter, which ExpensePaymentMethods to fetch.
   */
  where?: Prisma.ExpensePaymentMethodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of ExpensePaymentMethods to fetch.
   */
  orderBy?:
    | Prisma.ExpensePaymentMethodOrderByWithRelationInput
    | Prisma.ExpensePaymentMethodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing ExpensePaymentMethods.
   */
  cursor?: Prisma.ExpensePaymentMethodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` ExpensePaymentMethods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` ExpensePaymentMethods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of ExpensePaymentMethods.
   */
  distinct?:
    | Prisma.ExpensePaymentMethodScalarFieldEnum
    | Prisma.ExpensePaymentMethodScalarFieldEnum[]
}

/**
 * ExpensePaymentMethod create
 */
export type ExpensePaymentMethodCreateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ExpensePaymentMethod
   */
  select?: Prisma.ExpensePaymentMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExpensePaymentMethod
   */
  omit?: Prisma.ExpensePaymentMethodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExpensePaymentMethodInclude<ExtArgs> | null
  /**
   * The data needed to create a ExpensePaymentMethod.
   */
  data: Prisma.XOR<
    Prisma.ExpensePaymentMethodCreateInput,
    Prisma.ExpensePaymentMethodUncheckedCreateInput
  >
}

/**
 * ExpensePaymentMethod createMany
 */
export type ExpensePaymentMethodCreateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many ExpensePaymentMethods.
   */
  data: Prisma.ExpensePaymentMethodCreateManyInput | Prisma.ExpensePaymentMethodCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ExpensePaymentMethod createManyAndReturn
 */
export type ExpensePaymentMethodCreateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ExpensePaymentMethod
   */
  select?: Prisma.ExpensePaymentMethodSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ExpensePaymentMethod
   */
  omit?: Prisma.ExpensePaymentMethodOmit<ExtArgs> | null
  /**
   * The data used to create many ExpensePaymentMethods.
   */
  data: Prisma.ExpensePaymentMethodCreateManyInput | Prisma.ExpensePaymentMethodCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExpensePaymentMethodIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ExpensePaymentMethod update
 */
export type ExpensePaymentMethodUpdateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ExpensePaymentMethod
   */
  select?: Prisma.ExpensePaymentMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExpensePaymentMethod
   */
  omit?: Prisma.ExpensePaymentMethodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExpensePaymentMethodInclude<ExtArgs> | null
  /**
   * The data needed to update a ExpensePaymentMethod.
   */
  data: Prisma.XOR<
    Prisma.ExpensePaymentMethodUpdateInput,
    Prisma.ExpensePaymentMethodUncheckedUpdateInput
  >
  /**
   * Choose, which ExpensePaymentMethod to update.
   */
  where: Prisma.ExpensePaymentMethodWhereUniqueInput
}

/**
 * ExpensePaymentMethod updateMany
 */
export type ExpensePaymentMethodUpdateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update ExpensePaymentMethods.
   */
  data: Prisma.XOR<
    Prisma.ExpensePaymentMethodUpdateManyMutationInput,
    Prisma.ExpensePaymentMethodUncheckedUpdateManyInput
  >
  /**
   * Filter which ExpensePaymentMethods to update
   */
  where?: Prisma.ExpensePaymentMethodWhereInput
  /**
   * Limit how many ExpensePaymentMethods to update.
   */
  limit?: number
}

/**
 * ExpensePaymentMethod updateManyAndReturn
 */
export type ExpensePaymentMethodUpdateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ExpensePaymentMethod
   */
  select?: Prisma.ExpensePaymentMethodSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ExpensePaymentMethod
   */
  omit?: Prisma.ExpensePaymentMethodOmit<ExtArgs> | null
  /**
   * The data used to update ExpensePaymentMethods.
   */
  data: Prisma.XOR<
    Prisma.ExpensePaymentMethodUpdateManyMutationInput,
    Prisma.ExpensePaymentMethodUncheckedUpdateManyInput
  >
  /**
   * Filter which ExpensePaymentMethods to update
   */
  where?: Prisma.ExpensePaymentMethodWhereInput
  /**
   * Limit how many ExpensePaymentMethods to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExpensePaymentMethodIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ExpensePaymentMethod upsert
 */
export type ExpensePaymentMethodUpsertArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ExpensePaymentMethod
   */
  select?: Prisma.ExpensePaymentMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExpensePaymentMethod
   */
  omit?: Prisma.ExpensePaymentMethodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExpensePaymentMethodInclude<ExtArgs> | null
  /**
   * The filter to search for the ExpensePaymentMethod to update in case it exists.
   */
  where: Prisma.ExpensePaymentMethodWhereUniqueInput
  /**
   * In case the ExpensePaymentMethod found by the `where` argument doesn't exist, create a new ExpensePaymentMethod with this data.
   */
  create: Prisma.XOR<
    Prisma.ExpensePaymentMethodCreateInput,
    Prisma.ExpensePaymentMethodUncheckedCreateInput
  >
  /**
   * In case the ExpensePaymentMethod was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<
    Prisma.ExpensePaymentMethodUpdateInput,
    Prisma.ExpensePaymentMethodUncheckedUpdateInput
  >
}

/**
 * ExpensePaymentMethod delete
 */
export type ExpensePaymentMethodDeleteArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ExpensePaymentMethod
   */
  select?: Prisma.ExpensePaymentMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExpensePaymentMethod
   */
  omit?: Prisma.ExpensePaymentMethodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExpensePaymentMethodInclude<ExtArgs> | null
  /**
   * Filter which ExpensePaymentMethod to delete.
   */
  where: Prisma.ExpensePaymentMethodWhereUniqueInput
}

/**
 * ExpensePaymentMethod deleteMany
 */
export type ExpensePaymentMethodDeleteManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which ExpensePaymentMethods to delete
   */
  where?: Prisma.ExpensePaymentMethodWhereInput
  /**
   * Limit how many ExpensePaymentMethods to delete.
   */
  limit?: number
}

/**
 * ExpensePaymentMethod without action
 */
export type ExpensePaymentMethodDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ExpensePaymentMethod
   */
  select?: Prisma.ExpensePaymentMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExpensePaymentMethod
   */
  omit?: Prisma.ExpensePaymentMethodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExpensePaymentMethodInclude<ExtArgs> | null
}
