/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `SourceOfIncome` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/client'
import type * as $Enums from '../enums'
import type * as Prisma from '../internal/prismaNamespace'

/**
 * Model SourceOfIncome
 *
 */
export type SourceOfIncomeModel =
  runtime.Types.Result.DefaultSelection<Prisma.$SourceOfIncomePayload>

export type AggregateSourceOfIncome = {
  _count: SourceOfIncomeCountAggregateOutputType | null
  _avg: SourceOfIncomeAvgAggregateOutputType | null
  _sum: SourceOfIncomeSumAggregateOutputType | null
  _min: SourceOfIncomeMinAggregateOutputType | null
  _max: SourceOfIncomeMaxAggregateOutputType | null
}

export type SourceOfIncomeAvgAggregateOutputType = {
  id: number | null
  category_id: number | null
  income: number | null
  user_id: number | null
}

export type SourceOfIncomeSumAggregateOutputType = {
  id: bigint | null
  category_id: bigint | null
  income: number | null
  user_id: bigint | null
}

export type SourceOfIncomeMinAggregateOutputType = {
  id: bigint | null
  name: string | null
  category_id: bigint | null
  income: number | null
  currency: string | null
  user_id: bigint | null
  created_at: Date | null
  updated_at: Date | null
}

export type SourceOfIncomeMaxAggregateOutputType = {
  id: bigint | null
  name: string | null
  category_id: bigint | null
  income: number | null
  currency: string | null
  user_id: bigint | null
  created_at: Date | null
  updated_at: Date | null
}

export type SourceOfIncomeCountAggregateOutputType = {
  id: number
  name: number
  category_id: number
  income: number
  currency: number
  user_id: number
  created_at: number
  updated_at: number
  _all: number
}

export type SourceOfIncomeAvgAggregateInputType = {
  id?: true
  category_id?: true
  income?: true
  user_id?: true
}

export type SourceOfIncomeSumAggregateInputType = {
  id?: true
  category_id?: true
  income?: true
  user_id?: true
}

export type SourceOfIncomeMinAggregateInputType = {
  id?: true
  name?: true
  category_id?: true
  income?: true
  currency?: true
  user_id?: true
  created_at?: true
  updated_at?: true
}

export type SourceOfIncomeMaxAggregateInputType = {
  id?: true
  name?: true
  category_id?: true
  income?: true
  currency?: true
  user_id?: true
  created_at?: true
  updated_at?: true
}

export type SourceOfIncomeCountAggregateInputType = {
  id?: true
  name?: true
  category_id?: true
  income?: true
  currency?: true
  user_id?: true
  created_at?: true
  updated_at?: true
  _all?: true
}

export type SourceOfIncomeAggregateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which SourceOfIncome to aggregate.
   */
  where?: Prisma.SourceOfIncomeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of SourceOfIncomes to fetch.
   */
  orderBy?:
    | Prisma.SourceOfIncomeOrderByWithRelationInput
    | Prisma.SourceOfIncomeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.SourceOfIncomeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` SourceOfIncomes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` SourceOfIncomes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned SourceOfIncomes
   **/
  _count?: true | SourceOfIncomeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to average
   **/
  _avg?: SourceOfIncomeAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to sum
   **/
  _sum?: SourceOfIncomeSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: SourceOfIncomeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: SourceOfIncomeMaxAggregateInputType
}

export type GetSourceOfIncomeAggregateType<T extends SourceOfIncomeAggregateArgs> = {
  [P in keyof T & keyof AggregateSourceOfIncome]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSourceOfIncome[P]>
    : Prisma.GetScalarType<T[P], AggregateSourceOfIncome[P]>
}

export type SourceOfIncomeGroupByArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.SourceOfIncomeWhereInput
  orderBy?:
    | Prisma.SourceOfIncomeOrderByWithAggregationInput
    | Prisma.SourceOfIncomeOrderByWithAggregationInput[]
  by: Prisma.SourceOfIncomeScalarFieldEnum[] | Prisma.SourceOfIncomeScalarFieldEnum
  having?: Prisma.SourceOfIncomeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SourceOfIncomeCountAggregateInputType | true
  _avg?: SourceOfIncomeAvgAggregateInputType
  _sum?: SourceOfIncomeSumAggregateInputType
  _min?: SourceOfIncomeMinAggregateInputType
  _max?: SourceOfIncomeMaxAggregateInputType
}

export type SourceOfIncomeGroupByOutputType = {
  id: bigint
  name: string
  category_id: bigint
  income: number
  currency: string
  user_id: bigint
  created_at: Date
  updated_at: Date
  _count: SourceOfIncomeCountAggregateOutputType | null
  _avg: SourceOfIncomeAvgAggregateOutputType | null
  _sum: SourceOfIncomeSumAggregateOutputType | null
  _min: SourceOfIncomeMinAggregateOutputType | null
  _max: SourceOfIncomeMaxAggregateOutputType | null
}

export type GetSourceOfIncomeGroupByPayload<T extends SourceOfIncomeGroupByArgs> =
  Prisma.PrismaPromise<
    Array<
      Prisma.PickEnumerable<SourceOfIncomeGroupByOutputType, T['by']> & {
        [P in keyof T & keyof SourceOfIncomeGroupByOutputType]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SourceOfIncomeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SourceOfIncomeGroupByOutputType[P]>
      }
    >
  >

export type SourceOfIncomeWhereInput = {
  AND?: Prisma.SourceOfIncomeWhereInput | Prisma.SourceOfIncomeWhereInput[]
  OR?: Prisma.SourceOfIncomeWhereInput[]
  NOT?: Prisma.SourceOfIncomeWhereInput | Prisma.SourceOfIncomeWhereInput[]
  id?: Prisma.BigIntFilter<'SourceOfIncome'> | bigint | number
  name?: Prisma.StringFilter<'SourceOfIncome'> | string
  category_id?: Prisma.BigIntFilter<'SourceOfIncome'> | bigint | number
  income?: Prisma.FloatFilter<'SourceOfIncome'> | number
  currency?: Prisma.StringFilter<'SourceOfIncome'> | string
  user_id?: Prisma.BigIntFilter<'SourceOfIncome'> | bigint | number
  created_at?: Prisma.DateTimeFilter<'SourceOfIncome'> | Date | string
  updated_at?: Prisma.DateTimeFilter<'SourceOfIncome'> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  category?: Prisma.XOR<Prisma.CategoryScalarRelationFilter, Prisma.CategoryWhereInput>
}

export type SourceOfIncomeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  category_id?: Prisma.SortOrder
  income?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  category?: Prisma.CategoryOrderByWithRelationInput
}

export type SourceOfIncomeWhereUniqueInput = Prisma.AtLeast<
  {
    id?: bigint | number
    AND?: Prisma.SourceOfIncomeWhereInput | Prisma.SourceOfIncomeWhereInput[]
    OR?: Prisma.SourceOfIncomeWhereInput[]
    NOT?: Prisma.SourceOfIncomeWhereInput | Prisma.SourceOfIncomeWhereInput[]
    name?: Prisma.StringFilter<'SourceOfIncome'> | string
    category_id?: Prisma.BigIntFilter<'SourceOfIncome'> | bigint | number
    income?: Prisma.FloatFilter<'SourceOfIncome'> | number
    currency?: Prisma.StringFilter<'SourceOfIncome'> | string
    user_id?: Prisma.BigIntFilter<'SourceOfIncome'> | bigint | number
    created_at?: Prisma.DateTimeFilter<'SourceOfIncome'> | Date | string
    updated_at?: Prisma.DateTimeFilter<'SourceOfIncome'> | Date | string
    user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
    category?: Prisma.XOR<Prisma.CategoryScalarRelationFilter, Prisma.CategoryWhereInput>
  },
  'id'
>

export type SourceOfIncomeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  category_id?: Prisma.SortOrder
  income?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  _count?: Prisma.SourceOfIncomeCountOrderByAggregateInput
  _avg?: Prisma.SourceOfIncomeAvgOrderByAggregateInput
  _max?: Prisma.SourceOfIncomeMaxOrderByAggregateInput
  _min?: Prisma.SourceOfIncomeMinOrderByAggregateInput
  _sum?: Prisma.SourceOfIncomeSumOrderByAggregateInput
}

export type SourceOfIncomeScalarWhereWithAggregatesInput = {
  AND?:
    | Prisma.SourceOfIncomeScalarWhereWithAggregatesInput
    | Prisma.SourceOfIncomeScalarWhereWithAggregatesInput[]
  OR?: Prisma.SourceOfIncomeScalarWhereWithAggregatesInput[]
  NOT?:
    | Prisma.SourceOfIncomeScalarWhereWithAggregatesInput
    | Prisma.SourceOfIncomeScalarWhereWithAggregatesInput[]
  id?: Prisma.BigIntWithAggregatesFilter<'SourceOfIncome'> | bigint | number
  name?: Prisma.StringWithAggregatesFilter<'SourceOfIncome'> | string
  category_id?: Prisma.BigIntWithAggregatesFilter<'SourceOfIncome'> | bigint | number
  income?: Prisma.FloatWithAggregatesFilter<'SourceOfIncome'> | number
  currency?: Prisma.StringWithAggregatesFilter<'SourceOfIncome'> | string
  user_id?: Prisma.BigIntWithAggregatesFilter<'SourceOfIncome'> | bigint | number
  created_at?: Prisma.DateTimeWithAggregatesFilter<'SourceOfIncome'> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<'SourceOfIncome'> | Date | string
}

export type SourceOfIncomeCreateInput = {
  id?: bigint | number
  name: string
  income?: number
  currency?: string
  created_at?: Date | string
  updated_at?: Date | string
  user: Prisma.UserCreateNestedOneWithoutSources_of_incomeInput
  category: Prisma.CategoryCreateNestedOneWithoutSources_of_incomeInput
}

export type SourceOfIncomeUncheckedCreateInput = {
  id?: bigint | number
  name: string
  category_id: bigint | number
  income?: number
  currency?: string
  user_id: bigint | number
  created_at?: Date | string
  updated_at?: Date | string
}

export type SourceOfIncomeUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  income?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutSources_of_incomeNestedInput
  category?: Prisma.CategoryUpdateOneRequiredWithoutSources_of_incomeNestedInput
}

export type SourceOfIncomeUncheckedUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  category_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  income?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SourceOfIncomeCreateManyInput = {
  id?: bigint | number
  name: string
  category_id: bigint | number
  income?: number
  currency?: string
  user_id: bigint | number
  created_at?: Date | string
  updated_at?: Date | string
}

export type SourceOfIncomeUpdateManyMutationInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  income?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SourceOfIncomeUncheckedUpdateManyInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  category_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  income?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SourceOfIncomeListRelationFilter = {
  every?: Prisma.SourceOfIncomeWhereInput
  some?: Prisma.SourceOfIncomeWhereInput
  none?: Prisma.SourceOfIncomeWhereInput
}

export type SourceOfIncomeOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SourceOfIncomeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  category_id?: Prisma.SortOrder
  income?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type SourceOfIncomeAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  category_id?: Prisma.SortOrder
  income?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
}

export type SourceOfIncomeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  category_id?: Prisma.SortOrder
  income?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type SourceOfIncomeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  category_id?: Prisma.SortOrder
  income?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type SourceOfIncomeSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  category_id?: Prisma.SortOrder
  income?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
}

export type SourceOfIncomeCreateNestedManyWithoutUserInput = {
  create?:
    | Prisma.XOR<
        Prisma.SourceOfIncomeCreateWithoutUserInput,
        Prisma.SourceOfIncomeUncheckedCreateWithoutUserInput
      >
    | Prisma.SourceOfIncomeCreateWithoutUserInput[]
    | Prisma.SourceOfIncomeUncheckedCreateWithoutUserInput[]
  connectOrCreate?:
    | Prisma.SourceOfIncomeCreateOrConnectWithoutUserInput
    | Prisma.SourceOfIncomeCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.SourceOfIncomeCreateManyUserInputEnvelope
  connect?: Prisma.SourceOfIncomeWhereUniqueInput | Prisma.SourceOfIncomeWhereUniqueInput[]
}

export type SourceOfIncomeUncheckedCreateNestedManyWithoutUserInput = {
  create?:
    | Prisma.XOR<
        Prisma.SourceOfIncomeCreateWithoutUserInput,
        Prisma.SourceOfIncomeUncheckedCreateWithoutUserInput
      >
    | Prisma.SourceOfIncomeCreateWithoutUserInput[]
    | Prisma.SourceOfIncomeUncheckedCreateWithoutUserInput[]
  connectOrCreate?:
    | Prisma.SourceOfIncomeCreateOrConnectWithoutUserInput
    | Prisma.SourceOfIncomeCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.SourceOfIncomeCreateManyUserInputEnvelope
  connect?: Prisma.SourceOfIncomeWhereUniqueInput | Prisma.SourceOfIncomeWhereUniqueInput[]
}

export type SourceOfIncomeUpdateManyWithoutUserNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.SourceOfIncomeCreateWithoutUserInput,
        Prisma.SourceOfIncomeUncheckedCreateWithoutUserInput
      >
    | Prisma.SourceOfIncomeCreateWithoutUserInput[]
    | Prisma.SourceOfIncomeUncheckedCreateWithoutUserInput[]
  connectOrCreate?:
    | Prisma.SourceOfIncomeCreateOrConnectWithoutUserInput
    | Prisma.SourceOfIncomeCreateOrConnectWithoutUserInput[]
  upsert?:
    | Prisma.SourceOfIncomeUpsertWithWhereUniqueWithoutUserInput
    | Prisma.SourceOfIncomeUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.SourceOfIncomeCreateManyUserInputEnvelope
  set?: Prisma.SourceOfIncomeWhereUniqueInput | Prisma.SourceOfIncomeWhereUniqueInput[]
  disconnect?: Prisma.SourceOfIncomeWhereUniqueInput | Prisma.SourceOfIncomeWhereUniqueInput[]
  delete?: Prisma.SourceOfIncomeWhereUniqueInput | Prisma.SourceOfIncomeWhereUniqueInput[]
  connect?: Prisma.SourceOfIncomeWhereUniqueInput | Prisma.SourceOfIncomeWhereUniqueInput[]
  update?:
    | Prisma.SourceOfIncomeUpdateWithWhereUniqueWithoutUserInput
    | Prisma.SourceOfIncomeUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?:
    | Prisma.SourceOfIncomeUpdateManyWithWhereWithoutUserInput
    | Prisma.SourceOfIncomeUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.SourceOfIncomeScalarWhereInput | Prisma.SourceOfIncomeScalarWhereInput[]
}

export type SourceOfIncomeUncheckedUpdateManyWithoutUserNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.SourceOfIncomeCreateWithoutUserInput,
        Prisma.SourceOfIncomeUncheckedCreateWithoutUserInput
      >
    | Prisma.SourceOfIncomeCreateWithoutUserInput[]
    | Prisma.SourceOfIncomeUncheckedCreateWithoutUserInput[]
  connectOrCreate?:
    | Prisma.SourceOfIncomeCreateOrConnectWithoutUserInput
    | Prisma.SourceOfIncomeCreateOrConnectWithoutUserInput[]
  upsert?:
    | Prisma.SourceOfIncomeUpsertWithWhereUniqueWithoutUserInput
    | Prisma.SourceOfIncomeUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.SourceOfIncomeCreateManyUserInputEnvelope
  set?: Prisma.SourceOfIncomeWhereUniqueInput | Prisma.SourceOfIncomeWhereUniqueInput[]
  disconnect?: Prisma.SourceOfIncomeWhereUniqueInput | Prisma.SourceOfIncomeWhereUniqueInput[]
  delete?: Prisma.SourceOfIncomeWhereUniqueInput | Prisma.SourceOfIncomeWhereUniqueInput[]
  connect?: Prisma.SourceOfIncomeWhereUniqueInput | Prisma.SourceOfIncomeWhereUniqueInput[]
  update?:
    | Prisma.SourceOfIncomeUpdateWithWhereUniqueWithoutUserInput
    | Prisma.SourceOfIncomeUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?:
    | Prisma.SourceOfIncomeUpdateManyWithWhereWithoutUserInput
    | Prisma.SourceOfIncomeUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.SourceOfIncomeScalarWhereInput | Prisma.SourceOfIncomeScalarWhereInput[]
}

export type SourceOfIncomeCreateNestedManyWithoutCategoryInput = {
  create?:
    | Prisma.XOR<
        Prisma.SourceOfIncomeCreateWithoutCategoryInput,
        Prisma.SourceOfIncomeUncheckedCreateWithoutCategoryInput
      >
    | Prisma.SourceOfIncomeCreateWithoutCategoryInput[]
    | Prisma.SourceOfIncomeUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?:
    | Prisma.SourceOfIncomeCreateOrConnectWithoutCategoryInput
    | Prisma.SourceOfIncomeCreateOrConnectWithoutCategoryInput[]
  createMany?: Prisma.SourceOfIncomeCreateManyCategoryInputEnvelope
  connect?: Prisma.SourceOfIncomeWhereUniqueInput | Prisma.SourceOfIncomeWhereUniqueInput[]
}

export type SourceOfIncomeUncheckedCreateNestedManyWithoutCategoryInput = {
  create?:
    | Prisma.XOR<
        Prisma.SourceOfIncomeCreateWithoutCategoryInput,
        Prisma.SourceOfIncomeUncheckedCreateWithoutCategoryInput
      >
    | Prisma.SourceOfIncomeCreateWithoutCategoryInput[]
    | Prisma.SourceOfIncomeUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?:
    | Prisma.SourceOfIncomeCreateOrConnectWithoutCategoryInput
    | Prisma.SourceOfIncomeCreateOrConnectWithoutCategoryInput[]
  createMany?: Prisma.SourceOfIncomeCreateManyCategoryInputEnvelope
  connect?: Prisma.SourceOfIncomeWhereUniqueInput | Prisma.SourceOfIncomeWhereUniqueInput[]
}

export type SourceOfIncomeUpdateManyWithoutCategoryNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.SourceOfIncomeCreateWithoutCategoryInput,
        Prisma.SourceOfIncomeUncheckedCreateWithoutCategoryInput
      >
    | Prisma.SourceOfIncomeCreateWithoutCategoryInput[]
    | Prisma.SourceOfIncomeUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?:
    | Prisma.SourceOfIncomeCreateOrConnectWithoutCategoryInput
    | Prisma.SourceOfIncomeCreateOrConnectWithoutCategoryInput[]
  upsert?:
    | Prisma.SourceOfIncomeUpsertWithWhereUniqueWithoutCategoryInput
    | Prisma.SourceOfIncomeUpsertWithWhereUniqueWithoutCategoryInput[]
  createMany?: Prisma.SourceOfIncomeCreateManyCategoryInputEnvelope
  set?: Prisma.SourceOfIncomeWhereUniqueInput | Prisma.SourceOfIncomeWhereUniqueInput[]
  disconnect?: Prisma.SourceOfIncomeWhereUniqueInput | Prisma.SourceOfIncomeWhereUniqueInput[]
  delete?: Prisma.SourceOfIncomeWhereUniqueInput | Prisma.SourceOfIncomeWhereUniqueInput[]
  connect?: Prisma.SourceOfIncomeWhereUniqueInput | Prisma.SourceOfIncomeWhereUniqueInput[]
  update?:
    | Prisma.SourceOfIncomeUpdateWithWhereUniqueWithoutCategoryInput
    | Prisma.SourceOfIncomeUpdateWithWhereUniqueWithoutCategoryInput[]
  updateMany?:
    | Prisma.SourceOfIncomeUpdateManyWithWhereWithoutCategoryInput
    | Prisma.SourceOfIncomeUpdateManyWithWhereWithoutCategoryInput[]
  deleteMany?: Prisma.SourceOfIncomeScalarWhereInput | Prisma.SourceOfIncomeScalarWhereInput[]
}

export type SourceOfIncomeUncheckedUpdateManyWithoutCategoryNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.SourceOfIncomeCreateWithoutCategoryInput,
        Prisma.SourceOfIncomeUncheckedCreateWithoutCategoryInput
      >
    | Prisma.SourceOfIncomeCreateWithoutCategoryInput[]
    | Prisma.SourceOfIncomeUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?:
    | Prisma.SourceOfIncomeCreateOrConnectWithoutCategoryInput
    | Prisma.SourceOfIncomeCreateOrConnectWithoutCategoryInput[]
  upsert?:
    | Prisma.SourceOfIncomeUpsertWithWhereUniqueWithoutCategoryInput
    | Prisma.SourceOfIncomeUpsertWithWhereUniqueWithoutCategoryInput[]
  createMany?: Prisma.SourceOfIncomeCreateManyCategoryInputEnvelope
  set?: Prisma.SourceOfIncomeWhereUniqueInput | Prisma.SourceOfIncomeWhereUniqueInput[]
  disconnect?: Prisma.SourceOfIncomeWhereUniqueInput | Prisma.SourceOfIncomeWhereUniqueInput[]
  delete?: Prisma.SourceOfIncomeWhereUniqueInput | Prisma.SourceOfIncomeWhereUniqueInput[]
  connect?: Prisma.SourceOfIncomeWhereUniqueInput | Prisma.SourceOfIncomeWhereUniqueInput[]
  update?:
    | Prisma.SourceOfIncomeUpdateWithWhereUniqueWithoutCategoryInput
    | Prisma.SourceOfIncomeUpdateWithWhereUniqueWithoutCategoryInput[]
  updateMany?:
    | Prisma.SourceOfIncomeUpdateManyWithWhereWithoutCategoryInput
    | Prisma.SourceOfIncomeUpdateManyWithWhereWithoutCategoryInput[]
  deleteMany?: Prisma.SourceOfIncomeScalarWhereInput | Prisma.SourceOfIncomeScalarWhereInput[]
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type SourceOfIncomeCreateWithoutUserInput = {
  id?: bigint | number
  name: string
  income?: number
  currency?: string
  created_at?: Date | string
  updated_at?: Date | string
  category: Prisma.CategoryCreateNestedOneWithoutSources_of_incomeInput
}

export type SourceOfIncomeUncheckedCreateWithoutUserInput = {
  id?: bigint | number
  name: string
  category_id: bigint | number
  income?: number
  currency?: string
  created_at?: Date | string
  updated_at?: Date | string
}

export type SourceOfIncomeCreateOrConnectWithoutUserInput = {
  where: Prisma.SourceOfIncomeWhereUniqueInput
  create: Prisma.XOR<
    Prisma.SourceOfIncomeCreateWithoutUserInput,
    Prisma.SourceOfIncomeUncheckedCreateWithoutUserInput
  >
}

export type SourceOfIncomeCreateManyUserInputEnvelope = {
  data: Prisma.SourceOfIncomeCreateManyUserInput | Prisma.SourceOfIncomeCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type SourceOfIncomeUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.SourceOfIncomeWhereUniqueInput
  update: Prisma.XOR<
    Prisma.SourceOfIncomeUpdateWithoutUserInput,
    Prisma.SourceOfIncomeUncheckedUpdateWithoutUserInput
  >
  create: Prisma.XOR<
    Prisma.SourceOfIncomeCreateWithoutUserInput,
    Prisma.SourceOfIncomeUncheckedCreateWithoutUserInput
  >
}

export type SourceOfIncomeUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.SourceOfIncomeWhereUniqueInput
  data: Prisma.XOR<
    Prisma.SourceOfIncomeUpdateWithoutUserInput,
    Prisma.SourceOfIncomeUncheckedUpdateWithoutUserInput
  >
}

export type SourceOfIncomeUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.SourceOfIncomeScalarWhereInput
  data: Prisma.XOR<
    Prisma.SourceOfIncomeUpdateManyMutationInput,
    Prisma.SourceOfIncomeUncheckedUpdateManyWithoutUserInput
  >
}

export type SourceOfIncomeScalarWhereInput = {
  AND?: Prisma.SourceOfIncomeScalarWhereInput | Prisma.SourceOfIncomeScalarWhereInput[]
  OR?: Prisma.SourceOfIncomeScalarWhereInput[]
  NOT?: Prisma.SourceOfIncomeScalarWhereInput | Prisma.SourceOfIncomeScalarWhereInput[]
  id?: Prisma.BigIntFilter<'SourceOfIncome'> | bigint | number
  name?: Prisma.StringFilter<'SourceOfIncome'> | string
  category_id?: Prisma.BigIntFilter<'SourceOfIncome'> | bigint | number
  income?: Prisma.FloatFilter<'SourceOfIncome'> | number
  currency?: Prisma.StringFilter<'SourceOfIncome'> | string
  user_id?: Prisma.BigIntFilter<'SourceOfIncome'> | bigint | number
  created_at?: Prisma.DateTimeFilter<'SourceOfIncome'> | Date | string
  updated_at?: Prisma.DateTimeFilter<'SourceOfIncome'> | Date | string
}

export type SourceOfIncomeCreateWithoutCategoryInput = {
  id?: bigint | number
  name: string
  income?: number
  currency?: string
  created_at?: Date | string
  updated_at?: Date | string
  user: Prisma.UserCreateNestedOneWithoutSources_of_incomeInput
}

export type SourceOfIncomeUncheckedCreateWithoutCategoryInput = {
  id?: bigint | number
  name: string
  income?: number
  currency?: string
  user_id: bigint | number
  created_at?: Date | string
  updated_at?: Date | string
}

export type SourceOfIncomeCreateOrConnectWithoutCategoryInput = {
  where: Prisma.SourceOfIncomeWhereUniqueInput
  create: Prisma.XOR<
    Prisma.SourceOfIncomeCreateWithoutCategoryInput,
    Prisma.SourceOfIncomeUncheckedCreateWithoutCategoryInput
  >
}

export type SourceOfIncomeCreateManyCategoryInputEnvelope = {
  data:
    | Prisma.SourceOfIncomeCreateManyCategoryInput
    | Prisma.SourceOfIncomeCreateManyCategoryInput[]
  skipDuplicates?: boolean
}

export type SourceOfIncomeUpsertWithWhereUniqueWithoutCategoryInput = {
  where: Prisma.SourceOfIncomeWhereUniqueInput
  update: Prisma.XOR<
    Prisma.SourceOfIncomeUpdateWithoutCategoryInput,
    Prisma.SourceOfIncomeUncheckedUpdateWithoutCategoryInput
  >
  create: Prisma.XOR<
    Prisma.SourceOfIncomeCreateWithoutCategoryInput,
    Prisma.SourceOfIncomeUncheckedCreateWithoutCategoryInput
  >
}

export type SourceOfIncomeUpdateWithWhereUniqueWithoutCategoryInput = {
  where: Prisma.SourceOfIncomeWhereUniqueInput
  data: Prisma.XOR<
    Prisma.SourceOfIncomeUpdateWithoutCategoryInput,
    Prisma.SourceOfIncomeUncheckedUpdateWithoutCategoryInput
  >
}

export type SourceOfIncomeUpdateManyWithWhereWithoutCategoryInput = {
  where: Prisma.SourceOfIncomeScalarWhereInput
  data: Prisma.XOR<
    Prisma.SourceOfIncomeUpdateManyMutationInput,
    Prisma.SourceOfIncomeUncheckedUpdateManyWithoutCategoryInput
  >
}

export type SourceOfIncomeCreateManyUserInput = {
  id?: bigint | number
  name: string
  category_id: bigint | number
  income?: number
  currency?: string
  created_at?: Date | string
  updated_at?: Date | string
}

export type SourceOfIncomeUpdateWithoutUserInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  income?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  category?: Prisma.CategoryUpdateOneRequiredWithoutSources_of_incomeNestedInput
}

export type SourceOfIncomeUncheckedUpdateWithoutUserInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  category_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  income?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SourceOfIncomeUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  category_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  income?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SourceOfIncomeCreateManyCategoryInput = {
  id?: bigint | number
  name: string
  income?: number
  currency?: string
  user_id: bigint | number
  created_at?: Date | string
  updated_at?: Date | string
}

export type SourceOfIncomeUpdateWithoutCategoryInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  income?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutSources_of_incomeNestedInput
}

export type SourceOfIncomeUncheckedUpdateWithoutCategoryInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  income?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SourceOfIncomeUncheckedUpdateManyWithoutCategoryInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  income?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SourceOfIncomeSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    name?: boolean
    category_id?: boolean
    income?: boolean
    currency?: boolean
    user_id?: boolean
    created_at?: boolean
    updated_at?: boolean
    user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
    category?: boolean | Prisma.CategoryDefaultArgs<ExtArgs>
  },
  ExtArgs['result']['sourceOfIncome']
>

export type SourceOfIncomeSelectCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    name?: boolean
    category_id?: boolean
    income?: boolean
    currency?: boolean
    user_id?: boolean
    created_at?: boolean
    updated_at?: boolean
    user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
    category?: boolean | Prisma.CategoryDefaultArgs<ExtArgs>
  },
  ExtArgs['result']['sourceOfIncome']
>

export type SourceOfIncomeSelectUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    name?: boolean
    category_id?: boolean
    income?: boolean
    currency?: boolean
    user_id?: boolean
    created_at?: boolean
    updated_at?: boolean
    user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
    category?: boolean | Prisma.CategoryDefaultArgs<ExtArgs>
  },
  ExtArgs['result']['sourceOfIncome']
>

export type SourceOfIncomeSelectScalar = {
  id?: boolean
  name?: boolean
  category_id?: boolean
  income?: boolean
  currency?: boolean
  user_id?: boolean
  created_at?: boolean
  updated_at?: boolean
}

export type SourceOfIncomeOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  'id' | 'name' | 'category_id' | 'income' | 'currency' | 'user_id' | 'created_at' | 'updated_at',
  ExtArgs['result']['sourceOfIncome']
>
export type SourceOfIncomeInclude<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  category?: boolean | Prisma.CategoryDefaultArgs<ExtArgs>
}
export type SourceOfIncomeIncludeCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  category?: boolean | Prisma.CategoryDefaultArgs<ExtArgs>
}
export type SourceOfIncomeIncludeUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  category?: boolean | Prisma.CategoryDefaultArgs<ExtArgs>
}

export type $SourceOfIncomePayload<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  name: 'SourceOfIncome'
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    category: Prisma.$CategoryPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      id: bigint
      name: string
      category_id: bigint
      income: number
      currency: string
      user_id: bigint
      created_at: Date
      updated_at: Date
    },
    ExtArgs['result']['sourceOfIncome']
  >
  composites: {}
}

export type SourceOfIncomeGetPayload<
  S extends boolean | null | undefined | SourceOfIncomeDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$SourceOfIncomePayload, S>

export type SourceOfIncomeCountArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = Omit<SourceOfIncomeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
  select?: SourceOfIncomeCountAggregateInputType | true
}

export interface SourceOfIncomeDelegate<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>['model']['SourceOfIncome']
    meta: { name: 'SourceOfIncome' }
  }
  /**
   * Find zero or one SourceOfIncome that matches the filter.
   * @param {SourceOfIncomeFindUniqueArgs} args - Arguments to find a SourceOfIncome
   * @example
   * // Get one SourceOfIncome
   * const sourceOfIncome = await prisma.sourceOfIncome.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SourceOfIncomeFindUniqueArgs>(
    args: Prisma.SelectSubset<T, SourceOfIncomeFindUniqueArgs<ExtArgs>>
  ): Prisma.Prisma__SourceOfIncomeClient<
    runtime.Types.Result.GetResult<
      Prisma.$SourceOfIncomePayload<ExtArgs>,
      T,
      'findUnique',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find one SourceOfIncome that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SourceOfIncomeFindUniqueOrThrowArgs} args - Arguments to find a SourceOfIncome
   * @example
   * // Get one SourceOfIncome
   * const sourceOfIncome = await prisma.sourceOfIncome.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SourceOfIncomeFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<T, SourceOfIncomeFindUniqueOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__SourceOfIncomeClient<
    runtime.Types.Result.GetResult<
      Prisma.$SourceOfIncomePayload<ExtArgs>,
      T,
      'findUniqueOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find the first SourceOfIncome that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourceOfIncomeFindFirstArgs} args - Arguments to find a SourceOfIncome
   * @example
   * // Get one SourceOfIncome
   * const sourceOfIncome = await prisma.sourceOfIncome.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SourceOfIncomeFindFirstArgs>(
    args?: Prisma.SelectSubset<T, SourceOfIncomeFindFirstArgs<ExtArgs>>
  ): Prisma.Prisma__SourceOfIncomeClient<
    runtime.Types.Result.GetResult<
      Prisma.$SourceOfIncomePayload<ExtArgs>,
      T,
      'findFirst',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find the first SourceOfIncome that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourceOfIncomeFindFirstOrThrowArgs} args - Arguments to find a SourceOfIncome
   * @example
   * // Get one SourceOfIncome
   * const sourceOfIncome = await prisma.sourceOfIncome.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SourceOfIncomeFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<T, SourceOfIncomeFindFirstOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__SourceOfIncomeClient<
    runtime.Types.Result.GetResult<
      Prisma.$SourceOfIncomePayload<ExtArgs>,
      T,
      'findFirstOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find zero or more SourceOfIncomes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourceOfIncomeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SourceOfIncomes
   * const sourceOfIncomes = await prisma.sourceOfIncome.findMany()
   *
   * // Get first 10 SourceOfIncomes
   * const sourceOfIncomes = await prisma.sourceOfIncome.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const sourceOfIncomeWithIdOnly = await prisma.sourceOfIncome.findMany({ select: { id: true } })
   *
   */
  findMany<T extends SourceOfIncomeFindManyArgs>(
    args?: Prisma.SelectSubset<T, SourceOfIncomeFindManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$SourceOfIncomePayload<ExtArgs>,
      T,
      'findMany',
      GlobalOmitOptions
    >
  >

  /**
   * Create a SourceOfIncome.
   * @param {SourceOfIncomeCreateArgs} args - Arguments to create a SourceOfIncome.
   * @example
   * // Create one SourceOfIncome
   * const SourceOfIncome = await prisma.sourceOfIncome.create({
   *   data: {
   *     // ... data to create a SourceOfIncome
   *   }
   * })
   *
   */
  create<T extends SourceOfIncomeCreateArgs>(
    args: Prisma.SelectSubset<T, SourceOfIncomeCreateArgs<ExtArgs>>
  ): Prisma.Prisma__SourceOfIncomeClient<
    runtime.Types.Result.GetResult<
      Prisma.$SourceOfIncomePayload<ExtArgs>,
      T,
      'create',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Create many SourceOfIncomes.
   * @param {SourceOfIncomeCreateManyArgs} args - Arguments to create many SourceOfIncomes.
   * @example
   * // Create many SourceOfIncomes
   * const sourceOfIncome = await prisma.sourceOfIncome.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends SourceOfIncomeCreateManyArgs>(
    args?: Prisma.SelectSubset<T, SourceOfIncomeCreateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SourceOfIncomes and returns the data saved in the database.
   * @param {SourceOfIncomeCreateManyAndReturnArgs} args - Arguments to create many SourceOfIncomes.
   * @example
   * // Create many SourceOfIncomes
   * const sourceOfIncome = await prisma.sourceOfIncome.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many SourceOfIncomes and only return the `id`
   * const sourceOfIncomeWithIdOnly = await prisma.sourceOfIncome.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends SourceOfIncomeCreateManyAndReturnArgs>(
    args?: Prisma.SelectSubset<T, SourceOfIncomeCreateManyAndReturnArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$SourceOfIncomePayload<ExtArgs>,
      T,
      'createManyAndReturn',
      GlobalOmitOptions
    >
  >

  /**
   * Delete a SourceOfIncome.
   * @param {SourceOfIncomeDeleteArgs} args - Arguments to delete one SourceOfIncome.
   * @example
   * // Delete one SourceOfIncome
   * const SourceOfIncome = await prisma.sourceOfIncome.delete({
   *   where: {
   *     // ... filter to delete one SourceOfIncome
   *   }
   * })
   *
   */
  delete<T extends SourceOfIncomeDeleteArgs>(
    args: Prisma.SelectSubset<T, SourceOfIncomeDeleteArgs<ExtArgs>>
  ): Prisma.Prisma__SourceOfIncomeClient<
    runtime.Types.Result.GetResult<
      Prisma.$SourceOfIncomePayload<ExtArgs>,
      T,
      'delete',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Update one SourceOfIncome.
   * @param {SourceOfIncomeUpdateArgs} args - Arguments to update one SourceOfIncome.
   * @example
   * // Update one SourceOfIncome
   * const sourceOfIncome = await prisma.sourceOfIncome.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends SourceOfIncomeUpdateArgs>(
    args: Prisma.SelectSubset<T, SourceOfIncomeUpdateArgs<ExtArgs>>
  ): Prisma.Prisma__SourceOfIncomeClient<
    runtime.Types.Result.GetResult<
      Prisma.$SourceOfIncomePayload<ExtArgs>,
      T,
      'update',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Delete zero or more SourceOfIncomes.
   * @param {SourceOfIncomeDeleteManyArgs} args - Arguments to filter SourceOfIncomes to delete.
   * @example
   * // Delete a few SourceOfIncomes
   * const { count } = await prisma.sourceOfIncome.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends SourceOfIncomeDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, SourceOfIncomeDeleteManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SourceOfIncomes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourceOfIncomeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SourceOfIncomes
   * const sourceOfIncome = await prisma.sourceOfIncome.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends SourceOfIncomeUpdateManyArgs>(
    args: Prisma.SelectSubset<T, SourceOfIncomeUpdateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SourceOfIncomes and returns the data updated in the database.
   * @param {SourceOfIncomeUpdateManyAndReturnArgs} args - Arguments to update many SourceOfIncomes.
   * @example
   * // Update many SourceOfIncomes
   * const sourceOfIncome = await prisma.sourceOfIncome.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more SourceOfIncomes and only return the `id`
   * const sourceOfIncomeWithIdOnly = await prisma.sourceOfIncome.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends SourceOfIncomeUpdateManyAndReturnArgs>(
    args: Prisma.SelectSubset<T, SourceOfIncomeUpdateManyAndReturnArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$SourceOfIncomePayload<ExtArgs>,
      T,
      'updateManyAndReturn',
      GlobalOmitOptions
    >
  >

  /**
   * Create or update one SourceOfIncome.
   * @param {SourceOfIncomeUpsertArgs} args - Arguments to update or create a SourceOfIncome.
   * @example
   * // Update or create a SourceOfIncome
   * const sourceOfIncome = await prisma.sourceOfIncome.upsert({
   *   create: {
   *     // ... data to create a SourceOfIncome
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SourceOfIncome we want to update
   *   }
   * })
   */
  upsert<T extends SourceOfIncomeUpsertArgs>(
    args: Prisma.SelectSubset<T, SourceOfIncomeUpsertArgs<ExtArgs>>
  ): Prisma.Prisma__SourceOfIncomeClient<
    runtime.Types.Result.GetResult<
      Prisma.$SourceOfIncomePayload<ExtArgs>,
      T,
      'upsert',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Count the number of SourceOfIncomes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourceOfIncomeCountArgs} args - Arguments to filter SourceOfIncomes to count.
   * @example
   * // Count the number of SourceOfIncomes
   * const count = await prisma.sourceOfIncome.count({
   *   where: {
   *     // ... the filter for the SourceOfIncomes we want to count
   *   }
   * })
   **/
  count<T extends SourceOfIncomeCountArgs>(
    args?: Prisma.Subset<T, SourceOfIncomeCountArgs>
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SourceOfIncomeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SourceOfIncome.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourceOfIncomeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends SourceOfIncomeAggregateArgs>(
    args: Prisma.Subset<T, SourceOfIncomeAggregateArgs>
  ): Prisma.PrismaPromise<GetSourceOfIncomeAggregateType<T>>

  /**
   * Group by SourceOfIncome.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourceOfIncomeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends SourceOfIncomeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SourceOfIncomeGroupByArgs['orderBy'] }
      : { orderBy?: SourceOfIncomeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [Error, 'Field ', P, ` in "having" needs to be provided in "by"`]
          }[HavingFields]
        : 'take' extends Prisma.Keys<T>
          ? 'orderBy' extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : 'skip' extends Prisma.Keys<T>
            ? 'orderBy' extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields],
  >(
    args: Prisma.SubsetIntersection<T, SourceOfIncomeGroupByArgs, OrderByArg> & InputErrors
  ): {} extends InputErrors ? GetSourceOfIncomeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
  /**
   * Fields of the SourceOfIncome model
   */
  readonly fields: SourceOfIncomeFieldRefs
}

/**
 * The delegate class that acts as a "Promise-like" for SourceOfIncome.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SourceOfIncomeClient<
  T,
  Null = never,
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: 'PrismaPromise'
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>
  ): Prisma.Prisma__UserClient<
    | runtime.Types.Result.GetResult<
        Prisma.$UserPayload<ExtArgs>,
        T,
        'findUniqueOrThrow',
        GlobalOmitOptions
      >
    | Null,
    Null,
    ExtArgs,
    GlobalOmitOptions
  >
  category<T extends Prisma.CategoryDefaultArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.CategoryDefaultArgs<ExtArgs>>
  ): Prisma.Prisma__CategoryClient<
    | runtime.Types.Result.GetResult<
        Prisma.$CategoryPayload<ExtArgs>,
        T,
        'findUniqueOrThrow',
        GlobalOmitOptions
      >
    | Null,
    Null,
    ExtArgs,
    GlobalOmitOptions
  >
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null,
    onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null
  ): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}

/**
 * Fields of the SourceOfIncome model
 */
export interface SourceOfIncomeFieldRefs {
  readonly id: Prisma.FieldRef<'SourceOfIncome', 'BigInt'>
  readonly name: Prisma.FieldRef<'SourceOfIncome', 'String'>
  readonly category_id: Prisma.FieldRef<'SourceOfIncome', 'BigInt'>
  readonly income: Prisma.FieldRef<'SourceOfIncome', 'Float'>
  readonly currency: Prisma.FieldRef<'SourceOfIncome', 'String'>
  readonly user_id: Prisma.FieldRef<'SourceOfIncome', 'BigInt'>
  readonly created_at: Prisma.FieldRef<'SourceOfIncome', 'DateTime'>
  readonly updated_at: Prisma.FieldRef<'SourceOfIncome', 'DateTime'>
}

// Custom InputTypes
/**
 * SourceOfIncome findUnique
 */
export type SourceOfIncomeFindUniqueArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the SourceOfIncome
   */
  select?: Prisma.SourceOfIncomeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceOfIncome
   */
  omit?: Prisma.SourceOfIncomeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SourceOfIncomeInclude<ExtArgs> | null
  /**
   * Filter, which SourceOfIncome to fetch.
   */
  where: Prisma.SourceOfIncomeWhereUniqueInput
}

/**
 * SourceOfIncome findUniqueOrThrow
 */
export type SourceOfIncomeFindUniqueOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the SourceOfIncome
   */
  select?: Prisma.SourceOfIncomeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceOfIncome
   */
  omit?: Prisma.SourceOfIncomeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SourceOfIncomeInclude<ExtArgs> | null
  /**
   * Filter, which SourceOfIncome to fetch.
   */
  where: Prisma.SourceOfIncomeWhereUniqueInput
}

/**
 * SourceOfIncome findFirst
 */
export type SourceOfIncomeFindFirstArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the SourceOfIncome
   */
  select?: Prisma.SourceOfIncomeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceOfIncome
   */
  omit?: Prisma.SourceOfIncomeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SourceOfIncomeInclude<ExtArgs> | null
  /**
   * Filter, which SourceOfIncome to fetch.
   */
  where?: Prisma.SourceOfIncomeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of SourceOfIncomes to fetch.
   */
  orderBy?:
    | Prisma.SourceOfIncomeOrderByWithRelationInput
    | Prisma.SourceOfIncomeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for SourceOfIncomes.
   */
  cursor?: Prisma.SourceOfIncomeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` SourceOfIncomes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` SourceOfIncomes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of SourceOfIncomes.
   */
  distinct?: Prisma.SourceOfIncomeScalarFieldEnum | Prisma.SourceOfIncomeScalarFieldEnum[]
}

/**
 * SourceOfIncome findFirstOrThrow
 */
export type SourceOfIncomeFindFirstOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the SourceOfIncome
   */
  select?: Prisma.SourceOfIncomeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceOfIncome
   */
  omit?: Prisma.SourceOfIncomeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SourceOfIncomeInclude<ExtArgs> | null
  /**
   * Filter, which SourceOfIncome to fetch.
   */
  where?: Prisma.SourceOfIncomeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of SourceOfIncomes to fetch.
   */
  orderBy?:
    | Prisma.SourceOfIncomeOrderByWithRelationInput
    | Prisma.SourceOfIncomeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for SourceOfIncomes.
   */
  cursor?: Prisma.SourceOfIncomeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` SourceOfIncomes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` SourceOfIncomes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of SourceOfIncomes.
   */
  distinct?: Prisma.SourceOfIncomeScalarFieldEnum | Prisma.SourceOfIncomeScalarFieldEnum[]
}

/**
 * SourceOfIncome findMany
 */
export type SourceOfIncomeFindManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the SourceOfIncome
   */
  select?: Prisma.SourceOfIncomeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceOfIncome
   */
  omit?: Prisma.SourceOfIncomeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SourceOfIncomeInclude<ExtArgs> | null
  /**
   * Filter, which SourceOfIncomes to fetch.
   */
  where?: Prisma.SourceOfIncomeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of SourceOfIncomes to fetch.
   */
  orderBy?:
    | Prisma.SourceOfIncomeOrderByWithRelationInput
    | Prisma.SourceOfIncomeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing SourceOfIncomes.
   */
  cursor?: Prisma.SourceOfIncomeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` SourceOfIncomes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` SourceOfIncomes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of SourceOfIncomes.
   */
  distinct?: Prisma.SourceOfIncomeScalarFieldEnum | Prisma.SourceOfIncomeScalarFieldEnum[]
}

/**
 * SourceOfIncome create
 */
export type SourceOfIncomeCreateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the SourceOfIncome
   */
  select?: Prisma.SourceOfIncomeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceOfIncome
   */
  omit?: Prisma.SourceOfIncomeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SourceOfIncomeInclude<ExtArgs> | null
  /**
   * The data needed to create a SourceOfIncome.
   */
  data: Prisma.XOR<Prisma.SourceOfIncomeCreateInput, Prisma.SourceOfIncomeUncheckedCreateInput>
}

/**
 * SourceOfIncome createMany
 */
export type SourceOfIncomeCreateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many SourceOfIncomes.
   */
  data: Prisma.SourceOfIncomeCreateManyInput | Prisma.SourceOfIncomeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SourceOfIncome createManyAndReturn
 */
export type SourceOfIncomeCreateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the SourceOfIncome
   */
  select?: Prisma.SourceOfIncomeSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SourceOfIncome
   */
  omit?: Prisma.SourceOfIncomeOmit<ExtArgs> | null
  /**
   * The data used to create many SourceOfIncomes.
   */
  data: Prisma.SourceOfIncomeCreateManyInput | Prisma.SourceOfIncomeCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SourceOfIncomeIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * SourceOfIncome update
 */
export type SourceOfIncomeUpdateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the SourceOfIncome
   */
  select?: Prisma.SourceOfIncomeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceOfIncome
   */
  omit?: Prisma.SourceOfIncomeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SourceOfIncomeInclude<ExtArgs> | null
  /**
   * The data needed to update a SourceOfIncome.
   */
  data: Prisma.XOR<Prisma.SourceOfIncomeUpdateInput, Prisma.SourceOfIncomeUncheckedUpdateInput>
  /**
   * Choose, which SourceOfIncome to update.
   */
  where: Prisma.SourceOfIncomeWhereUniqueInput
}

/**
 * SourceOfIncome updateMany
 */
export type SourceOfIncomeUpdateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update SourceOfIncomes.
   */
  data: Prisma.XOR<
    Prisma.SourceOfIncomeUpdateManyMutationInput,
    Prisma.SourceOfIncomeUncheckedUpdateManyInput
  >
  /**
   * Filter which SourceOfIncomes to update
   */
  where?: Prisma.SourceOfIncomeWhereInput
  /**
   * Limit how many SourceOfIncomes to update.
   */
  limit?: number
}

/**
 * SourceOfIncome updateManyAndReturn
 */
export type SourceOfIncomeUpdateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the SourceOfIncome
   */
  select?: Prisma.SourceOfIncomeSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SourceOfIncome
   */
  omit?: Prisma.SourceOfIncomeOmit<ExtArgs> | null
  /**
   * The data used to update SourceOfIncomes.
   */
  data: Prisma.XOR<
    Prisma.SourceOfIncomeUpdateManyMutationInput,
    Prisma.SourceOfIncomeUncheckedUpdateManyInput
  >
  /**
   * Filter which SourceOfIncomes to update
   */
  where?: Prisma.SourceOfIncomeWhereInput
  /**
   * Limit how many SourceOfIncomes to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SourceOfIncomeIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * SourceOfIncome upsert
 */
export type SourceOfIncomeUpsertArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the SourceOfIncome
   */
  select?: Prisma.SourceOfIncomeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceOfIncome
   */
  omit?: Prisma.SourceOfIncomeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SourceOfIncomeInclude<ExtArgs> | null
  /**
   * The filter to search for the SourceOfIncome to update in case it exists.
   */
  where: Prisma.SourceOfIncomeWhereUniqueInput
  /**
   * In case the SourceOfIncome found by the `where` argument doesn't exist, create a new SourceOfIncome with this data.
   */
  create: Prisma.XOR<Prisma.SourceOfIncomeCreateInput, Prisma.SourceOfIncomeUncheckedCreateInput>
  /**
   * In case the SourceOfIncome was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SourceOfIncomeUpdateInput, Prisma.SourceOfIncomeUncheckedUpdateInput>
}

/**
 * SourceOfIncome delete
 */
export type SourceOfIncomeDeleteArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the SourceOfIncome
   */
  select?: Prisma.SourceOfIncomeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceOfIncome
   */
  omit?: Prisma.SourceOfIncomeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SourceOfIncomeInclude<ExtArgs> | null
  /**
   * Filter which SourceOfIncome to delete.
   */
  where: Prisma.SourceOfIncomeWhereUniqueInput
}

/**
 * SourceOfIncome deleteMany
 */
export type SourceOfIncomeDeleteManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which SourceOfIncomes to delete
   */
  where?: Prisma.SourceOfIncomeWhereInput
  /**
   * Limit how many SourceOfIncomes to delete.
   */
  limit?: number
}

/**
 * SourceOfIncome without action
 */
export type SourceOfIncomeDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the SourceOfIncome
   */
  select?: Prisma.SourceOfIncomeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceOfIncome
   */
  omit?: Prisma.SourceOfIncomeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SourceOfIncomeInclude<ExtArgs> | null
}
