/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `UserSourceOfIncome` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/client'
import type * as $Enums from '../enums'
import type * as Prisma from '../internal/prismaNamespace'

/**
 * Model UserSourceOfIncome
 *
 */
export type UserSourceOfIncomeModel =
  runtime.Types.Result.DefaultSelection<Prisma.$UserSourceOfIncomePayload>

export type AggregateUserSourceOfIncome = {
  _count: UserSourceOfIncomeCountAggregateOutputType | null
  _avg: UserSourceOfIncomeAvgAggregateOutputType | null
  _sum: UserSourceOfIncomeSumAggregateOutputType | null
  _min: UserSourceOfIncomeMinAggregateOutputType | null
  _max: UserSourceOfIncomeMaxAggregateOutputType | null
}

export type UserSourceOfIncomeAvgAggregateOutputType = {
  user_id: number | null
  source_of_income_id: number | null
}

export type UserSourceOfIncomeSumAggregateOutputType = {
  user_id: bigint | null
  source_of_income_id: bigint | null
}

export type UserSourceOfIncomeMinAggregateOutputType = {
  user_id: bigint | null
  source_of_income_id: bigint | null
}

export type UserSourceOfIncomeMaxAggregateOutputType = {
  user_id: bigint | null
  source_of_income_id: bigint | null
}

export type UserSourceOfIncomeCountAggregateOutputType = {
  user_id: number
  source_of_income_id: number
  _all: number
}

export type UserSourceOfIncomeAvgAggregateInputType = {
  user_id?: true
  source_of_income_id?: true
}

export type UserSourceOfIncomeSumAggregateInputType = {
  user_id?: true
  source_of_income_id?: true
}

export type UserSourceOfIncomeMinAggregateInputType = {
  user_id?: true
  source_of_income_id?: true
}

export type UserSourceOfIncomeMaxAggregateInputType = {
  user_id?: true
  source_of_income_id?: true
}

export type UserSourceOfIncomeCountAggregateInputType = {
  user_id?: true
  source_of_income_id?: true
  _all?: true
}

export type UserSourceOfIncomeAggregateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which UserSourceOfIncome to aggregate.
   */
  where?: Prisma.UserSourceOfIncomeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of UserSourceOfIncomes to fetch.
   */
  orderBy?:
    | Prisma.UserSourceOfIncomeOrderByWithRelationInput
    | Prisma.UserSourceOfIncomeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.UserSourceOfIncomeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` UserSourceOfIncomes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` UserSourceOfIncomes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned UserSourceOfIncomes
   **/
  _count?: true | UserSourceOfIncomeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to average
   **/
  _avg?: UserSourceOfIncomeAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to sum
   **/
  _sum?: UserSourceOfIncomeSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: UserSourceOfIncomeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: UserSourceOfIncomeMaxAggregateInputType
}

export type GetUserSourceOfIncomeAggregateType<T extends UserSourceOfIncomeAggregateArgs> = {
  [P in keyof T & keyof AggregateUserSourceOfIncome]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUserSourceOfIncome[P]>
    : Prisma.GetScalarType<T[P], AggregateUserSourceOfIncome[P]>
}

export type UserSourceOfIncomeGroupByArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.UserSourceOfIncomeWhereInput
  orderBy?:
    | Prisma.UserSourceOfIncomeOrderByWithAggregationInput
    | Prisma.UserSourceOfIncomeOrderByWithAggregationInput[]
  by: Prisma.UserSourceOfIncomeScalarFieldEnum[] | Prisma.UserSourceOfIncomeScalarFieldEnum
  having?: Prisma.UserSourceOfIncomeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserSourceOfIncomeCountAggregateInputType | true
  _avg?: UserSourceOfIncomeAvgAggregateInputType
  _sum?: UserSourceOfIncomeSumAggregateInputType
  _min?: UserSourceOfIncomeMinAggregateInputType
  _max?: UserSourceOfIncomeMaxAggregateInputType
}

export type UserSourceOfIncomeGroupByOutputType = {
  user_id: bigint
  source_of_income_id: bigint
  _count: UserSourceOfIncomeCountAggregateOutputType | null
  _avg: UserSourceOfIncomeAvgAggregateOutputType | null
  _sum: UserSourceOfIncomeSumAggregateOutputType | null
  _min: UserSourceOfIncomeMinAggregateOutputType | null
  _max: UserSourceOfIncomeMaxAggregateOutputType | null
}

export type GetUserSourceOfIncomeGroupByPayload<T extends UserSourceOfIncomeGroupByArgs> =
  Prisma.PrismaPromise<
    Array<
      Prisma.PickEnumerable<UserSourceOfIncomeGroupByOutputType, T['by']> & {
        [P in keyof T & keyof UserSourceOfIncomeGroupByOutputType]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserSourceOfIncomeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserSourceOfIncomeGroupByOutputType[P]>
      }
    >
  >

export type UserSourceOfIncomeWhereInput = {
  AND?: Prisma.UserSourceOfIncomeWhereInput | Prisma.UserSourceOfIncomeWhereInput[]
  OR?: Prisma.UserSourceOfIncomeWhereInput[]
  NOT?: Prisma.UserSourceOfIncomeWhereInput | Prisma.UserSourceOfIncomeWhereInput[]
  user_id?: Prisma.BigIntFilter<'UserSourceOfIncome'> | bigint | number
  source_of_income_id?: Prisma.BigIntFilter<'UserSourceOfIncome'> | bigint | number
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  source_of_income?: Prisma.XOR<
    Prisma.SourceOfIncomeScalarRelationFilter,
    Prisma.SourceOfIncomeWhereInput
  >
}

export type UserSourceOfIncomeOrderByWithRelationInput = {
  user_id?: Prisma.SortOrder
  source_of_income_id?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  source_of_income?: Prisma.SourceOfIncomeOrderByWithRelationInput
}

export type UserSourceOfIncomeWhereUniqueInput = Prisma.AtLeast<
  {
    user_id_source_of_income_id?: Prisma.UserSourceOfIncomeUser_idSource_of_income_idCompoundUniqueInput
    AND?: Prisma.UserSourceOfIncomeWhereInput | Prisma.UserSourceOfIncomeWhereInput[]
    OR?: Prisma.UserSourceOfIncomeWhereInput[]
    NOT?: Prisma.UserSourceOfIncomeWhereInput | Prisma.UserSourceOfIncomeWhereInput[]
    user_id?: Prisma.BigIntFilter<'UserSourceOfIncome'> | bigint | number
    source_of_income_id?: Prisma.BigIntFilter<'UserSourceOfIncome'> | bigint | number
    user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
    source_of_income?: Prisma.XOR<
      Prisma.SourceOfIncomeScalarRelationFilter,
      Prisma.SourceOfIncomeWhereInput
    >
  },
  'user_id_source_of_income_id'
>

export type UserSourceOfIncomeOrderByWithAggregationInput = {
  user_id?: Prisma.SortOrder
  source_of_income_id?: Prisma.SortOrder
  _count?: Prisma.UserSourceOfIncomeCountOrderByAggregateInput
  _avg?: Prisma.UserSourceOfIncomeAvgOrderByAggregateInput
  _max?: Prisma.UserSourceOfIncomeMaxOrderByAggregateInput
  _min?: Prisma.UserSourceOfIncomeMinOrderByAggregateInput
  _sum?: Prisma.UserSourceOfIncomeSumOrderByAggregateInput
}

export type UserSourceOfIncomeScalarWhereWithAggregatesInput = {
  AND?:
    | Prisma.UserSourceOfIncomeScalarWhereWithAggregatesInput
    | Prisma.UserSourceOfIncomeScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserSourceOfIncomeScalarWhereWithAggregatesInput[]
  NOT?:
    | Prisma.UserSourceOfIncomeScalarWhereWithAggregatesInput
    | Prisma.UserSourceOfIncomeScalarWhereWithAggregatesInput[]
  user_id?: Prisma.BigIntWithAggregatesFilter<'UserSourceOfIncome'> | bigint | number
  source_of_income_id?: Prisma.BigIntWithAggregatesFilter<'UserSourceOfIncome'> | bigint | number
}

export type UserSourceOfIncomeCreateInput = {
  user: Prisma.UserCreateNestedOneWithoutSources_of_incomeInput
  source_of_income: Prisma.SourceOfIncomeCreateNestedOneWithoutUsersInput
}

export type UserSourceOfIncomeUncheckedCreateInput = {
  user_id: bigint | number
  source_of_income_id: bigint | number
}

export type UserSourceOfIncomeUpdateInput = {
  user?: Prisma.UserUpdateOneRequiredWithoutSources_of_incomeNestedInput
  source_of_income?: Prisma.SourceOfIncomeUpdateOneRequiredWithoutUsersNestedInput
}

export type UserSourceOfIncomeUncheckedUpdateInput = {
  user_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  source_of_income_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type UserSourceOfIncomeCreateManyInput = {
  user_id: bigint | number
  source_of_income_id: bigint | number
}

export type UserSourceOfIncomeUpdateManyMutationInput = {}

export type UserSourceOfIncomeUncheckedUpdateManyInput = {
  user_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  source_of_income_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type UserSourceOfIncomeListRelationFilter = {
  every?: Prisma.UserSourceOfIncomeWhereInput
  some?: Prisma.UserSourceOfIncomeWhereInput
  none?: Prisma.UserSourceOfIncomeWhereInput
}

export type UserSourceOfIncomeOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type UserSourceOfIncomeUser_idSource_of_income_idCompoundUniqueInput = {
  user_id: bigint | number
  source_of_income_id: bigint | number
}

export type UserSourceOfIncomeCountOrderByAggregateInput = {
  user_id?: Prisma.SortOrder
  source_of_income_id?: Prisma.SortOrder
}

export type UserSourceOfIncomeAvgOrderByAggregateInput = {
  user_id?: Prisma.SortOrder
  source_of_income_id?: Prisma.SortOrder
}

export type UserSourceOfIncomeMaxOrderByAggregateInput = {
  user_id?: Prisma.SortOrder
  source_of_income_id?: Prisma.SortOrder
}

export type UserSourceOfIncomeMinOrderByAggregateInput = {
  user_id?: Prisma.SortOrder
  source_of_income_id?: Prisma.SortOrder
}

export type UserSourceOfIncomeSumOrderByAggregateInput = {
  user_id?: Prisma.SortOrder
  source_of_income_id?: Prisma.SortOrder
}

export type UserSourceOfIncomeCreateNestedManyWithoutUserInput = {
  create?:
    | Prisma.XOR<
        Prisma.UserSourceOfIncomeCreateWithoutUserInput,
        Prisma.UserSourceOfIncomeUncheckedCreateWithoutUserInput
      >
    | Prisma.UserSourceOfIncomeCreateWithoutUserInput[]
    | Prisma.UserSourceOfIncomeUncheckedCreateWithoutUserInput[]
  connectOrCreate?:
    | Prisma.UserSourceOfIncomeCreateOrConnectWithoutUserInput
    | Prisma.UserSourceOfIncomeCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserSourceOfIncomeCreateManyUserInputEnvelope
  connect?: Prisma.UserSourceOfIncomeWhereUniqueInput | Prisma.UserSourceOfIncomeWhereUniqueInput[]
}

export type UserSourceOfIncomeUncheckedCreateNestedManyWithoutUserInput = {
  create?:
    | Prisma.XOR<
        Prisma.UserSourceOfIncomeCreateWithoutUserInput,
        Prisma.UserSourceOfIncomeUncheckedCreateWithoutUserInput
      >
    | Prisma.UserSourceOfIncomeCreateWithoutUserInput[]
    | Prisma.UserSourceOfIncomeUncheckedCreateWithoutUserInput[]
  connectOrCreate?:
    | Prisma.UserSourceOfIncomeCreateOrConnectWithoutUserInput
    | Prisma.UserSourceOfIncomeCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserSourceOfIncomeCreateManyUserInputEnvelope
  connect?: Prisma.UserSourceOfIncomeWhereUniqueInput | Prisma.UserSourceOfIncomeWhereUniqueInput[]
}

export type UserSourceOfIncomeUpdateManyWithoutUserNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.UserSourceOfIncomeCreateWithoutUserInput,
        Prisma.UserSourceOfIncomeUncheckedCreateWithoutUserInput
      >
    | Prisma.UserSourceOfIncomeCreateWithoutUserInput[]
    | Prisma.UserSourceOfIncomeUncheckedCreateWithoutUserInput[]
  connectOrCreate?:
    | Prisma.UserSourceOfIncomeCreateOrConnectWithoutUserInput
    | Prisma.UserSourceOfIncomeCreateOrConnectWithoutUserInput[]
  upsert?:
    | Prisma.UserSourceOfIncomeUpsertWithWhereUniqueWithoutUserInput
    | Prisma.UserSourceOfIncomeUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserSourceOfIncomeCreateManyUserInputEnvelope
  set?: Prisma.UserSourceOfIncomeWhereUniqueInput | Prisma.UserSourceOfIncomeWhereUniqueInput[]
  disconnect?:
    | Prisma.UserSourceOfIncomeWhereUniqueInput
    | Prisma.UserSourceOfIncomeWhereUniqueInput[]
  delete?: Prisma.UserSourceOfIncomeWhereUniqueInput | Prisma.UserSourceOfIncomeWhereUniqueInput[]
  connect?: Prisma.UserSourceOfIncomeWhereUniqueInput | Prisma.UserSourceOfIncomeWhereUniqueInput[]
  update?:
    | Prisma.UserSourceOfIncomeUpdateWithWhereUniqueWithoutUserInput
    | Prisma.UserSourceOfIncomeUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?:
    | Prisma.UserSourceOfIncomeUpdateManyWithWhereWithoutUserInput
    | Prisma.UserSourceOfIncomeUpdateManyWithWhereWithoutUserInput[]
  deleteMany?:
    | Prisma.UserSourceOfIncomeScalarWhereInput
    | Prisma.UserSourceOfIncomeScalarWhereInput[]
}

export type UserSourceOfIncomeUncheckedUpdateManyWithoutUserNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.UserSourceOfIncomeCreateWithoutUserInput,
        Prisma.UserSourceOfIncomeUncheckedCreateWithoutUserInput
      >
    | Prisma.UserSourceOfIncomeCreateWithoutUserInput[]
    | Prisma.UserSourceOfIncomeUncheckedCreateWithoutUserInput[]
  connectOrCreate?:
    | Prisma.UserSourceOfIncomeCreateOrConnectWithoutUserInput
    | Prisma.UserSourceOfIncomeCreateOrConnectWithoutUserInput[]
  upsert?:
    | Prisma.UserSourceOfIncomeUpsertWithWhereUniqueWithoutUserInput
    | Prisma.UserSourceOfIncomeUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserSourceOfIncomeCreateManyUserInputEnvelope
  set?: Prisma.UserSourceOfIncomeWhereUniqueInput | Prisma.UserSourceOfIncomeWhereUniqueInput[]
  disconnect?:
    | Prisma.UserSourceOfIncomeWhereUniqueInput
    | Prisma.UserSourceOfIncomeWhereUniqueInput[]
  delete?: Prisma.UserSourceOfIncomeWhereUniqueInput | Prisma.UserSourceOfIncomeWhereUniqueInput[]
  connect?: Prisma.UserSourceOfIncomeWhereUniqueInput | Prisma.UserSourceOfIncomeWhereUniqueInput[]
  update?:
    | Prisma.UserSourceOfIncomeUpdateWithWhereUniqueWithoutUserInput
    | Prisma.UserSourceOfIncomeUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?:
    | Prisma.UserSourceOfIncomeUpdateManyWithWhereWithoutUserInput
    | Prisma.UserSourceOfIncomeUpdateManyWithWhereWithoutUserInput[]
  deleteMany?:
    | Prisma.UserSourceOfIncomeScalarWhereInput
    | Prisma.UserSourceOfIncomeScalarWhereInput[]
}

export type UserSourceOfIncomeCreateNestedManyWithoutSource_of_incomeInput = {
  create?:
    | Prisma.XOR<
        Prisma.UserSourceOfIncomeCreateWithoutSource_of_incomeInput,
        Prisma.UserSourceOfIncomeUncheckedCreateWithoutSource_of_incomeInput
      >
    | Prisma.UserSourceOfIncomeCreateWithoutSource_of_incomeInput[]
    | Prisma.UserSourceOfIncomeUncheckedCreateWithoutSource_of_incomeInput[]
  connectOrCreate?:
    | Prisma.UserSourceOfIncomeCreateOrConnectWithoutSource_of_incomeInput
    | Prisma.UserSourceOfIncomeCreateOrConnectWithoutSource_of_incomeInput[]
  createMany?: Prisma.UserSourceOfIncomeCreateManySource_of_incomeInputEnvelope
  connect?: Prisma.UserSourceOfIncomeWhereUniqueInput | Prisma.UserSourceOfIncomeWhereUniqueInput[]
}

export type UserSourceOfIncomeUncheckedCreateNestedManyWithoutSource_of_incomeInput = {
  create?:
    | Prisma.XOR<
        Prisma.UserSourceOfIncomeCreateWithoutSource_of_incomeInput,
        Prisma.UserSourceOfIncomeUncheckedCreateWithoutSource_of_incomeInput
      >
    | Prisma.UserSourceOfIncomeCreateWithoutSource_of_incomeInput[]
    | Prisma.UserSourceOfIncomeUncheckedCreateWithoutSource_of_incomeInput[]
  connectOrCreate?:
    | Prisma.UserSourceOfIncomeCreateOrConnectWithoutSource_of_incomeInput
    | Prisma.UserSourceOfIncomeCreateOrConnectWithoutSource_of_incomeInput[]
  createMany?: Prisma.UserSourceOfIncomeCreateManySource_of_incomeInputEnvelope
  connect?: Prisma.UserSourceOfIncomeWhereUniqueInput | Prisma.UserSourceOfIncomeWhereUniqueInput[]
}

export type UserSourceOfIncomeUpdateManyWithoutSource_of_incomeNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.UserSourceOfIncomeCreateWithoutSource_of_incomeInput,
        Prisma.UserSourceOfIncomeUncheckedCreateWithoutSource_of_incomeInput
      >
    | Prisma.UserSourceOfIncomeCreateWithoutSource_of_incomeInput[]
    | Prisma.UserSourceOfIncomeUncheckedCreateWithoutSource_of_incomeInput[]
  connectOrCreate?:
    | Prisma.UserSourceOfIncomeCreateOrConnectWithoutSource_of_incomeInput
    | Prisma.UserSourceOfIncomeCreateOrConnectWithoutSource_of_incomeInput[]
  upsert?:
    | Prisma.UserSourceOfIncomeUpsertWithWhereUniqueWithoutSource_of_incomeInput
    | Prisma.UserSourceOfIncomeUpsertWithWhereUniqueWithoutSource_of_incomeInput[]
  createMany?: Prisma.UserSourceOfIncomeCreateManySource_of_incomeInputEnvelope
  set?: Prisma.UserSourceOfIncomeWhereUniqueInput | Prisma.UserSourceOfIncomeWhereUniqueInput[]
  disconnect?:
    | Prisma.UserSourceOfIncomeWhereUniqueInput
    | Prisma.UserSourceOfIncomeWhereUniqueInput[]
  delete?: Prisma.UserSourceOfIncomeWhereUniqueInput | Prisma.UserSourceOfIncomeWhereUniqueInput[]
  connect?: Prisma.UserSourceOfIncomeWhereUniqueInput | Prisma.UserSourceOfIncomeWhereUniqueInput[]
  update?:
    | Prisma.UserSourceOfIncomeUpdateWithWhereUniqueWithoutSource_of_incomeInput
    | Prisma.UserSourceOfIncomeUpdateWithWhereUniqueWithoutSource_of_incomeInput[]
  updateMany?:
    | Prisma.UserSourceOfIncomeUpdateManyWithWhereWithoutSource_of_incomeInput
    | Prisma.UserSourceOfIncomeUpdateManyWithWhereWithoutSource_of_incomeInput[]
  deleteMany?:
    | Prisma.UserSourceOfIncomeScalarWhereInput
    | Prisma.UserSourceOfIncomeScalarWhereInput[]
}

export type UserSourceOfIncomeUncheckedUpdateManyWithoutSource_of_incomeNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.UserSourceOfIncomeCreateWithoutSource_of_incomeInput,
        Prisma.UserSourceOfIncomeUncheckedCreateWithoutSource_of_incomeInput
      >
    | Prisma.UserSourceOfIncomeCreateWithoutSource_of_incomeInput[]
    | Prisma.UserSourceOfIncomeUncheckedCreateWithoutSource_of_incomeInput[]
  connectOrCreate?:
    | Prisma.UserSourceOfIncomeCreateOrConnectWithoutSource_of_incomeInput
    | Prisma.UserSourceOfIncomeCreateOrConnectWithoutSource_of_incomeInput[]
  upsert?:
    | Prisma.UserSourceOfIncomeUpsertWithWhereUniqueWithoutSource_of_incomeInput
    | Prisma.UserSourceOfIncomeUpsertWithWhereUniqueWithoutSource_of_incomeInput[]
  createMany?: Prisma.UserSourceOfIncomeCreateManySource_of_incomeInputEnvelope
  set?: Prisma.UserSourceOfIncomeWhereUniqueInput | Prisma.UserSourceOfIncomeWhereUniqueInput[]
  disconnect?:
    | Prisma.UserSourceOfIncomeWhereUniqueInput
    | Prisma.UserSourceOfIncomeWhereUniqueInput[]
  delete?: Prisma.UserSourceOfIncomeWhereUniqueInput | Prisma.UserSourceOfIncomeWhereUniqueInput[]
  connect?: Prisma.UserSourceOfIncomeWhereUniqueInput | Prisma.UserSourceOfIncomeWhereUniqueInput[]
  update?:
    | Prisma.UserSourceOfIncomeUpdateWithWhereUniqueWithoutSource_of_incomeInput
    | Prisma.UserSourceOfIncomeUpdateWithWhereUniqueWithoutSource_of_incomeInput[]
  updateMany?:
    | Prisma.UserSourceOfIncomeUpdateManyWithWhereWithoutSource_of_incomeInput
    | Prisma.UserSourceOfIncomeUpdateManyWithWhereWithoutSource_of_incomeInput[]
  deleteMany?:
    | Prisma.UserSourceOfIncomeScalarWhereInput
    | Prisma.UserSourceOfIncomeScalarWhereInput[]
}

export type UserSourceOfIncomeCreateWithoutUserInput = {
  source_of_income: Prisma.SourceOfIncomeCreateNestedOneWithoutUsersInput
}

export type UserSourceOfIncomeUncheckedCreateWithoutUserInput = {
  source_of_income_id: bigint | number
}

export type UserSourceOfIncomeCreateOrConnectWithoutUserInput = {
  where: Prisma.UserSourceOfIncomeWhereUniqueInput
  create: Prisma.XOR<
    Prisma.UserSourceOfIncomeCreateWithoutUserInput,
    Prisma.UserSourceOfIncomeUncheckedCreateWithoutUserInput
  >
}

export type UserSourceOfIncomeCreateManyUserInputEnvelope = {
  data:
    | Prisma.UserSourceOfIncomeCreateManyUserInput
    | Prisma.UserSourceOfIncomeCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type UserSourceOfIncomeUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserSourceOfIncomeWhereUniqueInput
  update: Prisma.XOR<
    Prisma.UserSourceOfIncomeUpdateWithoutUserInput,
    Prisma.UserSourceOfIncomeUncheckedUpdateWithoutUserInput
  >
  create: Prisma.XOR<
    Prisma.UserSourceOfIncomeCreateWithoutUserInput,
    Prisma.UserSourceOfIncomeUncheckedCreateWithoutUserInput
  >
}

export type UserSourceOfIncomeUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserSourceOfIncomeWhereUniqueInput
  data: Prisma.XOR<
    Prisma.UserSourceOfIncomeUpdateWithoutUserInput,
    Prisma.UserSourceOfIncomeUncheckedUpdateWithoutUserInput
  >
}

export type UserSourceOfIncomeUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.UserSourceOfIncomeScalarWhereInput
  data: Prisma.XOR<
    Prisma.UserSourceOfIncomeUpdateManyMutationInput,
    Prisma.UserSourceOfIncomeUncheckedUpdateManyWithoutUserInput
  >
}

export type UserSourceOfIncomeScalarWhereInput = {
  AND?: Prisma.UserSourceOfIncomeScalarWhereInput | Prisma.UserSourceOfIncomeScalarWhereInput[]
  OR?: Prisma.UserSourceOfIncomeScalarWhereInput[]
  NOT?: Prisma.UserSourceOfIncomeScalarWhereInput | Prisma.UserSourceOfIncomeScalarWhereInput[]
  user_id?: Prisma.BigIntFilter<'UserSourceOfIncome'> | bigint | number
  source_of_income_id?: Prisma.BigIntFilter<'UserSourceOfIncome'> | bigint | number
}

export type UserSourceOfIncomeCreateWithoutSource_of_incomeInput = {
  user: Prisma.UserCreateNestedOneWithoutSources_of_incomeInput
}

export type UserSourceOfIncomeUncheckedCreateWithoutSource_of_incomeInput = {
  user_id: bigint | number
}

export type UserSourceOfIncomeCreateOrConnectWithoutSource_of_incomeInput = {
  where: Prisma.UserSourceOfIncomeWhereUniqueInput
  create: Prisma.XOR<
    Prisma.UserSourceOfIncomeCreateWithoutSource_of_incomeInput,
    Prisma.UserSourceOfIncomeUncheckedCreateWithoutSource_of_incomeInput
  >
}

export type UserSourceOfIncomeCreateManySource_of_incomeInputEnvelope = {
  data:
    | Prisma.UserSourceOfIncomeCreateManySource_of_incomeInput
    | Prisma.UserSourceOfIncomeCreateManySource_of_incomeInput[]
  skipDuplicates?: boolean
}

export type UserSourceOfIncomeUpsertWithWhereUniqueWithoutSource_of_incomeInput = {
  where: Prisma.UserSourceOfIncomeWhereUniqueInput
  update: Prisma.XOR<
    Prisma.UserSourceOfIncomeUpdateWithoutSource_of_incomeInput,
    Prisma.UserSourceOfIncomeUncheckedUpdateWithoutSource_of_incomeInput
  >
  create: Prisma.XOR<
    Prisma.UserSourceOfIncomeCreateWithoutSource_of_incomeInput,
    Prisma.UserSourceOfIncomeUncheckedCreateWithoutSource_of_incomeInput
  >
}

export type UserSourceOfIncomeUpdateWithWhereUniqueWithoutSource_of_incomeInput = {
  where: Prisma.UserSourceOfIncomeWhereUniqueInput
  data: Prisma.XOR<
    Prisma.UserSourceOfIncomeUpdateWithoutSource_of_incomeInput,
    Prisma.UserSourceOfIncomeUncheckedUpdateWithoutSource_of_incomeInput
  >
}

export type UserSourceOfIncomeUpdateManyWithWhereWithoutSource_of_incomeInput = {
  where: Prisma.UserSourceOfIncomeScalarWhereInput
  data: Prisma.XOR<
    Prisma.UserSourceOfIncomeUpdateManyMutationInput,
    Prisma.UserSourceOfIncomeUncheckedUpdateManyWithoutSource_of_incomeInput
  >
}

export type UserSourceOfIncomeCreateManyUserInput = {
  source_of_income_id: bigint | number
}

export type UserSourceOfIncomeUpdateWithoutUserInput = {
  source_of_income?: Prisma.SourceOfIncomeUpdateOneRequiredWithoutUsersNestedInput
}

export type UserSourceOfIncomeUncheckedUpdateWithoutUserInput = {
  source_of_income_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type UserSourceOfIncomeUncheckedUpdateManyWithoutUserInput = {
  source_of_income_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type UserSourceOfIncomeCreateManySource_of_incomeInput = {
  user_id: bigint | number
}

export type UserSourceOfIncomeUpdateWithoutSource_of_incomeInput = {
  user?: Prisma.UserUpdateOneRequiredWithoutSources_of_incomeNestedInput
}

export type UserSourceOfIncomeUncheckedUpdateWithoutSource_of_incomeInput = {
  user_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type UserSourceOfIncomeUncheckedUpdateManyWithoutSource_of_incomeInput = {
  user_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type UserSourceOfIncomeSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    user_id?: boolean
    source_of_income_id?: boolean
    user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
    source_of_income?: boolean | Prisma.SourceOfIncomeDefaultArgs<ExtArgs>
  },
  ExtArgs['result']['userSourceOfIncome']
>

export type UserSourceOfIncomeSelectCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    user_id?: boolean
    source_of_income_id?: boolean
    user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
    source_of_income?: boolean | Prisma.SourceOfIncomeDefaultArgs<ExtArgs>
  },
  ExtArgs['result']['userSourceOfIncome']
>

export type UserSourceOfIncomeSelectUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    user_id?: boolean
    source_of_income_id?: boolean
    user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
    source_of_income?: boolean | Prisma.SourceOfIncomeDefaultArgs<ExtArgs>
  },
  ExtArgs['result']['userSourceOfIncome']
>

export type UserSourceOfIncomeSelectScalar = {
  user_id?: boolean
  source_of_income_id?: boolean
}

export type UserSourceOfIncomeOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  'user_id' | 'source_of_income_id',
  ExtArgs['result']['userSourceOfIncome']
>
export type UserSourceOfIncomeInclude<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  source_of_income?: boolean | Prisma.SourceOfIncomeDefaultArgs<ExtArgs>
}
export type UserSourceOfIncomeIncludeCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  source_of_income?: boolean | Prisma.SourceOfIncomeDefaultArgs<ExtArgs>
}
export type UserSourceOfIncomeIncludeUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  source_of_income?: boolean | Prisma.SourceOfIncomeDefaultArgs<ExtArgs>
}

export type $UserSourceOfIncomePayload<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  name: 'UserSourceOfIncome'
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    source_of_income: Prisma.$SourceOfIncomePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      user_id: bigint
      source_of_income_id: bigint
    },
    ExtArgs['result']['userSourceOfIncome']
  >
  composites: {}
}

export type UserSourceOfIncomeGetPayload<
  S extends boolean | null | undefined | UserSourceOfIncomeDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$UserSourceOfIncomePayload, S>

export type UserSourceOfIncomeCountArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = Omit<UserSourceOfIncomeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
  select?: UserSourceOfIncomeCountAggregateInputType | true
}

export interface UserSourceOfIncomeDelegate<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>['model']['UserSourceOfIncome']
    meta: { name: 'UserSourceOfIncome' }
  }
  /**
   * Find zero or one UserSourceOfIncome that matches the filter.
   * @param {UserSourceOfIncomeFindUniqueArgs} args - Arguments to find a UserSourceOfIncome
   * @example
   * // Get one UserSourceOfIncome
   * const userSourceOfIncome = await prisma.userSourceOfIncome.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserSourceOfIncomeFindUniqueArgs>(
    args: Prisma.SelectSubset<T, UserSourceOfIncomeFindUniqueArgs<ExtArgs>>
  ): Prisma.Prisma__UserSourceOfIncomeClient<
    runtime.Types.Result.GetResult<
      Prisma.$UserSourceOfIncomePayload<ExtArgs>,
      T,
      'findUnique',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find one UserSourceOfIncome that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserSourceOfIncomeFindUniqueOrThrowArgs} args - Arguments to find a UserSourceOfIncome
   * @example
   * // Get one UserSourceOfIncome
   * const userSourceOfIncome = await prisma.userSourceOfIncome.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserSourceOfIncomeFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<T, UserSourceOfIncomeFindUniqueOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__UserSourceOfIncomeClient<
    runtime.Types.Result.GetResult<
      Prisma.$UserSourceOfIncomePayload<ExtArgs>,
      T,
      'findUniqueOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find the first UserSourceOfIncome that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserSourceOfIncomeFindFirstArgs} args - Arguments to find a UserSourceOfIncome
   * @example
   * // Get one UserSourceOfIncome
   * const userSourceOfIncome = await prisma.userSourceOfIncome.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserSourceOfIncomeFindFirstArgs>(
    args?: Prisma.SelectSubset<T, UserSourceOfIncomeFindFirstArgs<ExtArgs>>
  ): Prisma.Prisma__UserSourceOfIncomeClient<
    runtime.Types.Result.GetResult<
      Prisma.$UserSourceOfIncomePayload<ExtArgs>,
      T,
      'findFirst',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find the first UserSourceOfIncome that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserSourceOfIncomeFindFirstOrThrowArgs} args - Arguments to find a UserSourceOfIncome
   * @example
   * // Get one UserSourceOfIncome
   * const userSourceOfIncome = await prisma.userSourceOfIncome.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserSourceOfIncomeFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<T, UserSourceOfIncomeFindFirstOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__UserSourceOfIncomeClient<
    runtime.Types.Result.GetResult<
      Prisma.$UserSourceOfIncomePayload<ExtArgs>,
      T,
      'findFirstOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find zero or more UserSourceOfIncomes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserSourceOfIncomeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UserSourceOfIncomes
   * const userSourceOfIncomes = await prisma.userSourceOfIncome.findMany()
   *
   * // Get first 10 UserSourceOfIncomes
   * const userSourceOfIncomes = await prisma.userSourceOfIncome.findMany({ take: 10 })
   *
   * // Only select the `user_id`
   * const userSourceOfIncomeWithUser_idOnly = await prisma.userSourceOfIncome.findMany({ select: { user_id: true } })
   *
   */
  findMany<T extends UserSourceOfIncomeFindManyArgs>(
    args?: Prisma.SelectSubset<T, UserSourceOfIncomeFindManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$UserSourceOfIncomePayload<ExtArgs>,
      T,
      'findMany',
      GlobalOmitOptions
    >
  >

  /**
   * Create a UserSourceOfIncome.
   * @param {UserSourceOfIncomeCreateArgs} args - Arguments to create a UserSourceOfIncome.
   * @example
   * // Create one UserSourceOfIncome
   * const UserSourceOfIncome = await prisma.userSourceOfIncome.create({
   *   data: {
   *     // ... data to create a UserSourceOfIncome
   *   }
   * })
   *
   */
  create<T extends UserSourceOfIncomeCreateArgs>(
    args: Prisma.SelectSubset<T, UserSourceOfIncomeCreateArgs<ExtArgs>>
  ): Prisma.Prisma__UserSourceOfIncomeClient<
    runtime.Types.Result.GetResult<
      Prisma.$UserSourceOfIncomePayload<ExtArgs>,
      T,
      'create',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Create many UserSourceOfIncomes.
   * @param {UserSourceOfIncomeCreateManyArgs} args - Arguments to create many UserSourceOfIncomes.
   * @example
   * // Create many UserSourceOfIncomes
   * const userSourceOfIncome = await prisma.userSourceOfIncome.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends UserSourceOfIncomeCreateManyArgs>(
    args?: Prisma.SelectSubset<T, UserSourceOfIncomeCreateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many UserSourceOfIncomes and returns the data saved in the database.
   * @param {UserSourceOfIncomeCreateManyAndReturnArgs} args - Arguments to create many UserSourceOfIncomes.
   * @example
   * // Create many UserSourceOfIncomes
   * const userSourceOfIncome = await prisma.userSourceOfIncome.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many UserSourceOfIncomes and only return the `user_id`
   * const userSourceOfIncomeWithUser_idOnly = await prisma.userSourceOfIncome.createManyAndReturn({
   *   select: { user_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends UserSourceOfIncomeCreateManyAndReturnArgs>(
    args?: Prisma.SelectSubset<T, UserSourceOfIncomeCreateManyAndReturnArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$UserSourceOfIncomePayload<ExtArgs>,
      T,
      'createManyAndReturn',
      GlobalOmitOptions
    >
  >

  /**
   * Delete a UserSourceOfIncome.
   * @param {UserSourceOfIncomeDeleteArgs} args - Arguments to delete one UserSourceOfIncome.
   * @example
   * // Delete one UserSourceOfIncome
   * const UserSourceOfIncome = await prisma.userSourceOfIncome.delete({
   *   where: {
   *     // ... filter to delete one UserSourceOfIncome
   *   }
   * })
   *
   */
  delete<T extends UserSourceOfIncomeDeleteArgs>(
    args: Prisma.SelectSubset<T, UserSourceOfIncomeDeleteArgs<ExtArgs>>
  ): Prisma.Prisma__UserSourceOfIncomeClient<
    runtime.Types.Result.GetResult<
      Prisma.$UserSourceOfIncomePayload<ExtArgs>,
      T,
      'delete',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Update one UserSourceOfIncome.
   * @param {UserSourceOfIncomeUpdateArgs} args - Arguments to update one UserSourceOfIncome.
   * @example
   * // Update one UserSourceOfIncome
   * const userSourceOfIncome = await prisma.userSourceOfIncome.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends UserSourceOfIncomeUpdateArgs>(
    args: Prisma.SelectSubset<T, UserSourceOfIncomeUpdateArgs<ExtArgs>>
  ): Prisma.Prisma__UserSourceOfIncomeClient<
    runtime.Types.Result.GetResult<
      Prisma.$UserSourceOfIncomePayload<ExtArgs>,
      T,
      'update',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Delete zero or more UserSourceOfIncomes.
   * @param {UserSourceOfIncomeDeleteManyArgs} args - Arguments to filter UserSourceOfIncomes to delete.
   * @example
   * // Delete a few UserSourceOfIncomes
   * const { count } = await prisma.userSourceOfIncome.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends UserSourceOfIncomeDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, UserSourceOfIncomeDeleteManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserSourceOfIncomes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserSourceOfIncomeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UserSourceOfIncomes
   * const userSourceOfIncome = await prisma.userSourceOfIncome.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends UserSourceOfIncomeUpdateManyArgs>(
    args: Prisma.SelectSubset<T, UserSourceOfIncomeUpdateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserSourceOfIncomes and returns the data updated in the database.
   * @param {UserSourceOfIncomeUpdateManyAndReturnArgs} args - Arguments to update many UserSourceOfIncomes.
   * @example
   * // Update many UserSourceOfIncomes
   * const userSourceOfIncome = await prisma.userSourceOfIncome.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more UserSourceOfIncomes and only return the `user_id`
   * const userSourceOfIncomeWithUser_idOnly = await prisma.userSourceOfIncome.updateManyAndReturn({
   *   select: { user_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends UserSourceOfIncomeUpdateManyAndReturnArgs>(
    args: Prisma.SelectSubset<T, UserSourceOfIncomeUpdateManyAndReturnArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$UserSourceOfIncomePayload<ExtArgs>,
      T,
      'updateManyAndReturn',
      GlobalOmitOptions
    >
  >

  /**
   * Create or update one UserSourceOfIncome.
   * @param {UserSourceOfIncomeUpsertArgs} args - Arguments to update or create a UserSourceOfIncome.
   * @example
   * // Update or create a UserSourceOfIncome
   * const userSourceOfIncome = await prisma.userSourceOfIncome.upsert({
   *   create: {
   *     // ... data to create a UserSourceOfIncome
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UserSourceOfIncome we want to update
   *   }
   * })
   */
  upsert<T extends UserSourceOfIncomeUpsertArgs>(
    args: Prisma.SelectSubset<T, UserSourceOfIncomeUpsertArgs<ExtArgs>>
  ): Prisma.Prisma__UserSourceOfIncomeClient<
    runtime.Types.Result.GetResult<
      Prisma.$UserSourceOfIncomePayload<ExtArgs>,
      T,
      'upsert',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Count the number of UserSourceOfIncomes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserSourceOfIncomeCountArgs} args - Arguments to filter UserSourceOfIncomes to count.
   * @example
   * // Count the number of UserSourceOfIncomes
   * const count = await prisma.userSourceOfIncome.count({
   *   where: {
   *     // ... the filter for the UserSourceOfIncomes we want to count
   *   }
   * })
   **/
  count<T extends UserSourceOfIncomeCountArgs>(
    args?: Prisma.Subset<T, UserSourceOfIncomeCountArgs>
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserSourceOfIncomeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UserSourceOfIncome.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserSourceOfIncomeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends UserSourceOfIncomeAggregateArgs>(
    args: Prisma.Subset<T, UserSourceOfIncomeAggregateArgs>
  ): Prisma.PrismaPromise<GetUserSourceOfIncomeAggregateType<T>>

  /**
   * Group by UserSourceOfIncome.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserSourceOfIncomeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends UserSourceOfIncomeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserSourceOfIncomeGroupByArgs['orderBy'] }
      : { orderBy?: UserSourceOfIncomeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [Error, 'Field ', P, ` in "having" needs to be provided in "by"`]
          }[HavingFields]
        : 'take' extends Prisma.Keys<T>
          ? 'orderBy' extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : 'skip' extends Prisma.Keys<T>
            ? 'orderBy' extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields],
  >(
    args: Prisma.SubsetIntersection<T, UserSourceOfIncomeGroupByArgs, OrderByArg> & InputErrors
  ): {} extends InputErrors
    ? GetUserSourceOfIncomeGroupByPayload<T>
    : Prisma.PrismaPromise<InputErrors>
  /**
   * Fields of the UserSourceOfIncome model
   */
  readonly fields: UserSourceOfIncomeFieldRefs
}

/**
 * The delegate class that acts as a "Promise-like" for UserSourceOfIncome.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserSourceOfIncomeClient<
  T,
  Null = never,
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: 'PrismaPromise'
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>
  ): Prisma.Prisma__UserClient<
    | runtime.Types.Result.GetResult<
        Prisma.$UserPayload<ExtArgs>,
        T,
        'findUniqueOrThrow',
        GlobalOmitOptions
      >
    | Null,
    Null,
    ExtArgs,
    GlobalOmitOptions
  >
  source_of_income<T extends Prisma.SourceOfIncomeDefaultArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.SourceOfIncomeDefaultArgs<ExtArgs>>
  ): Prisma.Prisma__SourceOfIncomeClient<
    | runtime.Types.Result.GetResult<
        Prisma.$SourceOfIncomePayload<ExtArgs>,
        T,
        'findUniqueOrThrow',
        GlobalOmitOptions
      >
    | Null,
    Null,
    ExtArgs,
    GlobalOmitOptions
  >
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null,
    onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null
  ): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}

/**
 * Fields of the UserSourceOfIncome model
 */
export interface UserSourceOfIncomeFieldRefs {
  readonly user_id: Prisma.FieldRef<'UserSourceOfIncome', 'BigInt'>
  readonly source_of_income_id: Prisma.FieldRef<'UserSourceOfIncome', 'BigInt'>
}

// Custom InputTypes
/**
 * UserSourceOfIncome findUnique
 */
export type UserSourceOfIncomeFindUniqueArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UserSourceOfIncome
   */
  select?: Prisma.UserSourceOfIncomeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserSourceOfIncome
   */
  omit?: Prisma.UserSourceOfIncomeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserSourceOfIncomeInclude<ExtArgs> | null
  /**
   * Filter, which UserSourceOfIncome to fetch.
   */
  where: Prisma.UserSourceOfIncomeWhereUniqueInput
}

/**
 * UserSourceOfIncome findUniqueOrThrow
 */
export type UserSourceOfIncomeFindUniqueOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UserSourceOfIncome
   */
  select?: Prisma.UserSourceOfIncomeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserSourceOfIncome
   */
  omit?: Prisma.UserSourceOfIncomeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserSourceOfIncomeInclude<ExtArgs> | null
  /**
   * Filter, which UserSourceOfIncome to fetch.
   */
  where: Prisma.UserSourceOfIncomeWhereUniqueInput
}

/**
 * UserSourceOfIncome findFirst
 */
export type UserSourceOfIncomeFindFirstArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UserSourceOfIncome
   */
  select?: Prisma.UserSourceOfIncomeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserSourceOfIncome
   */
  omit?: Prisma.UserSourceOfIncomeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserSourceOfIncomeInclude<ExtArgs> | null
  /**
   * Filter, which UserSourceOfIncome to fetch.
   */
  where?: Prisma.UserSourceOfIncomeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of UserSourceOfIncomes to fetch.
   */
  orderBy?:
    | Prisma.UserSourceOfIncomeOrderByWithRelationInput
    | Prisma.UserSourceOfIncomeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for UserSourceOfIncomes.
   */
  cursor?: Prisma.UserSourceOfIncomeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` UserSourceOfIncomes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` UserSourceOfIncomes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of UserSourceOfIncomes.
   */
  distinct?: Prisma.UserSourceOfIncomeScalarFieldEnum | Prisma.UserSourceOfIncomeScalarFieldEnum[]
}

/**
 * UserSourceOfIncome findFirstOrThrow
 */
export type UserSourceOfIncomeFindFirstOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UserSourceOfIncome
   */
  select?: Prisma.UserSourceOfIncomeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserSourceOfIncome
   */
  omit?: Prisma.UserSourceOfIncomeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserSourceOfIncomeInclude<ExtArgs> | null
  /**
   * Filter, which UserSourceOfIncome to fetch.
   */
  where?: Prisma.UserSourceOfIncomeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of UserSourceOfIncomes to fetch.
   */
  orderBy?:
    | Prisma.UserSourceOfIncomeOrderByWithRelationInput
    | Prisma.UserSourceOfIncomeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for UserSourceOfIncomes.
   */
  cursor?: Prisma.UserSourceOfIncomeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` UserSourceOfIncomes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` UserSourceOfIncomes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of UserSourceOfIncomes.
   */
  distinct?: Prisma.UserSourceOfIncomeScalarFieldEnum | Prisma.UserSourceOfIncomeScalarFieldEnum[]
}

/**
 * UserSourceOfIncome findMany
 */
export type UserSourceOfIncomeFindManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UserSourceOfIncome
   */
  select?: Prisma.UserSourceOfIncomeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserSourceOfIncome
   */
  omit?: Prisma.UserSourceOfIncomeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserSourceOfIncomeInclude<ExtArgs> | null
  /**
   * Filter, which UserSourceOfIncomes to fetch.
   */
  where?: Prisma.UserSourceOfIncomeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of UserSourceOfIncomes to fetch.
   */
  orderBy?:
    | Prisma.UserSourceOfIncomeOrderByWithRelationInput
    | Prisma.UserSourceOfIncomeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing UserSourceOfIncomes.
   */
  cursor?: Prisma.UserSourceOfIncomeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` UserSourceOfIncomes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` UserSourceOfIncomes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of UserSourceOfIncomes.
   */
  distinct?: Prisma.UserSourceOfIncomeScalarFieldEnum | Prisma.UserSourceOfIncomeScalarFieldEnum[]
}

/**
 * UserSourceOfIncome create
 */
export type UserSourceOfIncomeCreateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UserSourceOfIncome
   */
  select?: Prisma.UserSourceOfIncomeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserSourceOfIncome
   */
  omit?: Prisma.UserSourceOfIncomeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserSourceOfIncomeInclude<ExtArgs> | null
  /**
   * The data needed to create a UserSourceOfIncome.
   */
  data: Prisma.XOR<
    Prisma.UserSourceOfIncomeCreateInput,
    Prisma.UserSourceOfIncomeUncheckedCreateInput
  >
}

/**
 * UserSourceOfIncome createMany
 */
export type UserSourceOfIncomeCreateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many UserSourceOfIncomes.
   */
  data: Prisma.UserSourceOfIncomeCreateManyInput | Prisma.UserSourceOfIncomeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * UserSourceOfIncome createManyAndReturn
 */
export type UserSourceOfIncomeCreateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UserSourceOfIncome
   */
  select?: Prisma.UserSourceOfIncomeSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserSourceOfIncome
   */
  omit?: Prisma.UserSourceOfIncomeOmit<ExtArgs> | null
  /**
   * The data used to create many UserSourceOfIncomes.
   */
  data: Prisma.UserSourceOfIncomeCreateManyInput | Prisma.UserSourceOfIncomeCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserSourceOfIncomeIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * UserSourceOfIncome update
 */
export type UserSourceOfIncomeUpdateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UserSourceOfIncome
   */
  select?: Prisma.UserSourceOfIncomeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserSourceOfIncome
   */
  omit?: Prisma.UserSourceOfIncomeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserSourceOfIncomeInclude<ExtArgs> | null
  /**
   * The data needed to update a UserSourceOfIncome.
   */
  data: Prisma.XOR<
    Prisma.UserSourceOfIncomeUpdateInput,
    Prisma.UserSourceOfIncomeUncheckedUpdateInput
  >
  /**
   * Choose, which UserSourceOfIncome to update.
   */
  where: Prisma.UserSourceOfIncomeWhereUniqueInput
}

/**
 * UserSourceOfIncome updateMany
 */
export type UserSourceOfIncomeUpdateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update UserSourceOfIncomes.
   */
  data: Prisma.XOR<
    Prisma.UserSourceOfIncomeUpdateManyMutationInput,
    Prisma.UserSourceOfIncomeUncheckedUpdateManyInput
  >
  /**
   * Filter which UserSourceOfIncomes to update
   */
  where?: Prisma.UserSourceOfIncomeWhereInput
  /**
   * Limit how many UserSourceOfIncomes to update.
   */
  limit?: number
}

/**
 * UserSourceOfIncome updateManyAndReturn
 */
export type UserSourceOfIncomeUpdateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UserSourceOfIncome
   */
  select?: Prisma.UserSourceOfIncomeSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserSourceOfIncome
   */
  omit?: Prisma.UserSourceOfIncomeOmit<ExtArgs> | null
  /**
   * The data used to update UserSourceOfIncomes.
   */
  data: Prisma.XOR<
    Prisma.UserSourceOfIncomeUpdateManyMutationInput,
    Prisma.UserSourceOfIncomeUncheckedUpdateManyInput
  >
  /**
   * Filter which UserSourceOfIncomes to update
   */
  where?: Prisma.UserSourceOfIncomeWhereInput
  /**
   * Limit how many UserSourceOfIncomes to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserSourceOfIncomeIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * UserSourceOfIncome upsert
 */
export type UserSourceOfIncomeUpsertArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UserSourceOfIncome
   */
  select?: Prisma.UserSourceOfIncomeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserSourceOfIncome
   */
  omit?: Prisma.UserSourceOfIncomeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserSourceOfIncomeInclude<ExtArgs> | null
  /**
   * The filter to search for the UserSourceOfIncome to update in case it exists.
   */
  where: Prisma.UserSourceOfIncomeWhereUniqueInput
  /**
   * In case the UserSourceOfIncome found by the `where` argument doesn't exist, create a new UserSourceOfIncome with this data.
   */
  create: Prisma.XOR<
    Prisma.UserSourceOfIncomeCreateInput,
    Prisma.UserSourceOfIncomeUncheckedCreateInput
  >
  /**
   * In case the UserSourceOfIncome was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<
    Prisma.UserSourceOfIncomeUpdateInput,
    Prisma.UserSourceOfIncomeUncheckedUpdateInput
  >
}

/**
 * UserSourceOfIncome delete
 */
export type UserSourceOfIncomeDeleteArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UserSourceOfIncome
   */
  select?: Prisma.UserSourceOfIncomeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserSourceOfIncome
   */
  omit?: Prisma.UserSourceOfIncomeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserSourceOfIncomeInclude<ExtArgs> | null
  /**
   * Filter which UserSourceOfIncome to delete.
   */
  where: Prisma.UserSourceOfIncomeWhereUniqueInput
}

/**
 * UserSourceOfIncome deleteMany
 */
export type UserSourceOfIncomeDeleteManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which UserSourceOfIncomes to delete
   */
  where?: Prisma.UserSourceOfIncomeWhereInput
  /**
   * Limit how many UserSourceOfIncomes to delete.
   */
  limit?: number
}

/**
 * UserSourceOfIncome without action
 */
export type UserSourceOfIncomeDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UserSourceOfIncome
   */
  select?: Prisma.UserSourceOfIncomeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserSourceOfIncome
   */
  omit?: Prisma.UserSourceOfIncomeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserSourceOfIncomeInclude<ExtArgs> | null
}
